// src/topics/polynomial-regression/questions.ts
import type { Question } from '../../engine/types';

export const polyQuestions: Question[] = [
  {
    id: 'poly-001',
    mode: 'nat',
    prompt: 'A degree-2 polynomial is fitted on normalized input u = x/3, giving ŷ(u) = 2u² + 3u + 1. What is the predicted ŷ at x = 3?',
    answer: 6,
    tolerance: 0.01,
    explanation: 'At x = 3, the normalized input is u = x/3 = 1. Then ŷ = 2·(1)² + 3·(1) + 1 = 2 + 3 + 1 = 6. Always convert x to u = x/x_max before evaluating the fitted polynomial.',
    concepts: ['polynomial-regression', 'prediction', 'basis expansion'],
    difficulty: 2,
    tags: ['formula', 'numerical'],
  },
  {
    id: 'poly-002',
    mode: 'nat',
    prompt: 'A degree-2 polynomial is fitted on normalized input u = x/3: ŷ = 0.9 + 1.2u + 0.5u². What is the predicted ŷ at x = 1.5?',
    answer: 1.625,
    tolerance: 0.001,
    explanation: 'u = 1.5/3 = 0.5, so ŷ = 0.9 + 1.2·0.5 + 0.5·(0.5)² = 0.9 + 0.6 + 0.125 = 1.625.',
    concepts: ['polynomial-regression', 'prediction'],
    difficulty: 2,
    tags: ['formula', 'numerical'],
  },
  {
    id: 'poly-003',
    mode: 'conceptual-mcq',
    prompt: 'Why does a high-degree polynomial regression overfit noisy data?',
    options: [
      'The normal equation becomes slower to compute for large d',
      'With d + 1 parameters the model has enough flexibility to fit the training noise, not just the signal — variance explodes on unseen points',
      'High degree makes the data points themselves noisier',
      'The test set becomes too small to evaluate the model',
    ],
    answer: 'B',
    explanation: 'A degree-d model has d + 1 free parameters. For large d the fitted curve can pass arbitrarily close to every training point — including the noise — producing wild oscillations that generalize badly (high variance).',
    trapExplanations: {
      A: 'Speed is not the issue; a 16×16 inversion is instant.',
      C: 'Degree is a model choice; it cannot change the noise in the data.',
      D: 'The test set size is set by the experimenter and is independent of the degree.',
    },
    concepts: ['polynomial-regression', 'overfitting', 'variance'],
    difficulty: 2,
    tags: ['conceptual'],
  },
  {
    id: 'poly-004',
    mode: 'visual',
    prompt: 'In the simulation, fit degree 1, then degree 2, then degree 15 on the same quadratic data (noise σ = 0.5). Which statement matches what you see?',
    options: [
      'Degree 1 wiggles through every point; degree 15 is a smooth gentle curve',
      'Degree 1 is a straight line missing the curvature; degree 2 hugs the parabola; degree 15 oscillates violently, especially near the ends',
      'All three fits are identical because least squares is unique',
      'Degree 15 has the lowest test error because it fits the training data best',
    ],
    answer: 'B',
    explanation: 'Degree 1 (line) has only bias — it cannot bend, so it misses the curvature. Degree 2 matches the true quadratic. Degree 15 interpolates the noise, oscillating sharply at the edges of the range (Runge-type behavior) — tiny train error, huge test error.',
    trapExplanations: {
      A: 'The opposite: degree 1 is the smooth line; degree 15 is the wiggly one.',
      C: 'The fits are different polynomials with different generalization.',
      D: 'Best TRAIN fit ≠ best TEST fit — the overfitted curve fails on unseen data.',
    },
    concepts: ['polynomial-regression', 'overfitting', 'visualization'],
    difficulty: 2,
    tags: ['visual'],
  },
  {
    id: 'poly-005',
    mode: 'gate-mcq',
    prompt: 'A student claims: "Increasing the polynomial degree always decreases the training error, so the highest degree is always the best model." What is wrong?',
    options: [
      'Training error does not fall monotonically with degree',
      'Training error does fall (monotonically, for least squares) — but the student measures the WRONG quantity: generalization needs held-out test error, which is U-shaped with degree',
      'The normal equation cannot solve degree ≥ 2',
      'Nothing — the highest degree is indeed always the best model',
    ],
    answer: 'B',
    explanation: 'For least-squares on nested polynomial bases, train MSE decreases as degree grows (never increases). But train error is in-sample and optimistic: the correct model-selection signal is held-out test error, which falls then rises (U-shape) — the bias-variance trade-off.',
    trapExplanations: {
      A: 'It does fall monotonically — that is exactly why the claim looks plausible.',
      C: 'The normal equation solves any degree with degree + 1 ≤ n (subject to conditioning).',
      D: 'The highest degree interpolates noise and generalizes worst.',
    },
    concepts: ['polynomial-regression', 'bias-variance', 'train-test-split'],
    difficulty: 3,
    tags: ['trap', 'conceptual'],
  },
  {
    id: 'poly-006',
    mode: 'matrix',
    prompt: 'A degree-3 polynomial is fitted with n = 100 training samples. The Vandermonde design matrix Φ has rows [1, u, u², u³]. What are its dimensions?',
    options: ['100 × 3', '100 × 4', '4 × 100', '3 × 3'],
    answer: 'B',
    explanation: 'One row per sample (100) and one column per basis function (degree 3 → columns 1, u, u², u³ → 4 columns). So Φ is 100 × 4, and the Gram matrix ΦᵀΦ is 4 × 4.',
    trapExplanations: {
      A: 'You forgot the constant/bias column — a degree-3 polynomial has 4 parameters (d + 1).',
      C: 'Rows are samples, columns are features — Φ is n × (d+1), not (d+1) × n.',
      D: 'That would be the size of ΦᵀΦ or the parameter count, not of Φ.',
    },
    concepts: ['polynomial-regression', 'vandermonde', 'matrix dimensions'],
    difficulty: 2,
    tags: ['matrix'],
  },
  {
    id: 'poly-007',
    mode: 'conceptual-mcq',
    prompt: 'With n = 10 training samples and degree d = 12, what does the normal equation produce?',
    options: [
      'A unique solution, because more basis functions always help',
      'Φ is 10 × 13 with rank ≤ 10, so ΦᵀΦ is singular — infinitely many θ interpolate the training data with zero error',
      'A runtime error because the powers are too large',
      'The same solution as ridge regression with λ = 0',
    ],
    answer: 'B',
    explanation: '13 parameters (degree 12 + bias) from 10 samples: the design matrix has rank at most 10 < 13, so the Gram matrix is singular and the normal equation has no unique answer — infinitely many polynomials pass exactly through the 10 points.',
    trapExplanations: {
      A: 'More parameters than samples means rank deficiency, not extra power.',
      C: 'The math is well-defined; the problem is rank, not overflow (u is normalized to [−1, 1]).',
      D: 'λ = 0 is the singular OLS case; ridge needs λ > 0 to be invertible.',
    },
    concepts: ['polynomial-regression', 'underdetermined', 'normal equation'],
    difficulty: 3,
    tags: ['conceptual', 'trap'],
  },
  {
    id: 'poly-008',
    mode: 'gate-mcq',
    prompt: 'Polynomial regression with degree d is best described as:',
    options: [
      'A nonlinear regression method, because the hypothesis is nonlinear in the input',
      'Linear regression on the basis-expanded features φ(u) = [1, u, u², …, u^d] — linear in the parameters θ',
      'A kernel method that cannot use the normal equation',
      'A classification algorithm applied to regression targets',
    ],
    answer: 'B',
    explanation: 'The model is a linear combination of fixed nonlinear functions of the input. It is nonlinear in x but linear in the parameters θ, so the normal equation and all least-squares theory apply unchanged. "Nonlinear regression" means nonlinear in θ, which is not the case here.',
    trapExplanations: {
      A: 'Nonlinearity in the INPUT does not make the model nonlinear in the parameters.',
      C: 'The normal equation applies directly to the Vandermonde Φ.',
      D: 'It is a regression (real-valued targets) method, not classification.',
    },
    concepts: ['polynomial-regression', 'basis expansion', 'linear-in-parameters'],
    difficulty: 3,
    tags: ['conceptual', 'trap'],
  },
];
