// src/topics/multiple-linear-regression/questions.ts
import type { Question } from '../../engine/types';

export const mlrQuestions: Question[] = [
  {
    id: 'mlr-001',
    mode: 'nat',
    prompt: 'For X = [[1,2,1],[2,1,1],[3,2,1],[4,1,1]] (design matrix with bias column last) and y = [5,6,9,10]: compute the normal equation solution θ = (XᵀX)⁻¹Xᵀy. What is w₁ (the weight on feature x₁)?',
    answer: 2,
    tolerance: 0.05,
    explanation: 'The data is exactly linear: y = 2x₁ + x₂ + 1, so the least-squares solution recovers θ = (2, 1, 1) exactly. w₁ = 2. (Check: row 3 → 2·3 + 2 + 1 = 9 ✓.)',
    concepts: ['multiple-linear-regression', 'normal equation', 'matrix operations'],
    difficulty: 4,
    tags: ['matrix', 'numerical', 'indirect'],
  },
  {
    id: 'mlr-002',
    mode: 'conceptual-mcq',
    prompt: 'Why must XᵀX be invertible for the normal equation θ = (XᵀX)⁻¹Xᵀy to give a unique solution?',
    options: [
      'Non-invertible XᵀX would make the computation too slow',
      'A singular XᵀX means X has linearly dependent columns — infinitely many θ fit the data equally well',
      'Invertibility guarantees the data is noise-free',
      'It does not need to be invertible — gradient descent always finds a unique answer',
    ],
    answer: 'B',
    explanation: 'XᵀX is singular exactly when X has linearly dependent columns (collinear features or n < d+1). Then the system XᵀXθ = Xᵀy has infinitely many solutions — the least-squares optimum is not unique.',
    trapExplanations: {
      A: 'Speed is irrelevant to uniqueness.',
      C: 'Invertibility is a rank property of X, not a property of noise.',
      D: 'GD converges to ONE of the infinite optima depending on initialization — not a unique solution.',
    },
    concepts: ['multiple-linear-regression', 'normal equation', 'matrix rank'],
    difficulty: 3,
    tags: ['conceptual'],
  },
  {
    id: 'mlr-003',
    mode: 'matrix',
    prompt: 'The design matrix X is 100 × 4 (n = 100 samples, d = 3 features + 1 bias column). What are the dimensions of XᵀX?',
    options: ['100 × 100', '4 × 4', '100 × 4', '4 × 100'],
    answer: 'B',
    explanation: 'X is n×(d+1) = 100×4, so Xᵀ is 4×100. The product XᵀX is (4×100)·(100×4) = 4×4. The inner dimensions (100) match; the Gram matrix is always square, sized (d+1)×(d+1) regardless of n.',
    trapExplanations: {
      A: 'That would be XXᵀ (100×100), not XᵀX.',
      C: 'XᵀX is square — the sample dimension n cancels in the product.',
      D: 'XᵀX is not transposed: Xᵀ is on the left, so the result is (d+1)×(d+1), not (d+1)×n.',
    },
    concepts: ['multiple-linear-regression', 'matrix dimensions'],
    difficulty: 2,
    tags: ['matrix'],
  },
  {
    id: 'mlr-004',
    mode: 'visual',
    prompt: 'In the simulation, you increase the noise σ from 0.1 to 2.0 while keeping n and the features fixed. What happens to the fitted hyperplane?',
    options: [
      'R² improves because more noise means more signal',
      'R² worsens — the points scatter further from the true hyperplane, so residual error grows',
      'R² is unchanged — least squares cancels noise exactly',
      'The weights w₁…w_d become exactly zero',
    ],
    answer: 'B',
    explanation: 'Larger σ spreads the training targets around the true hyperplane. The OLS fit still minimizes MSE, but the irreducible noise remains in the residuals, pushing R² down toward 0 (it cannot be negative here because the bias column is present).',
    trapExplanations: {
      A: 'Noise is not signal — it inflates SS_res.',
      C: 'Least squares cannot cancel noise; it only minimizes its effect on θ.',
      D: 'Weights stay near their true values; only the residuals grow.',
    },
    concepts: ['multiple-linear-regression', 'noise', 'r-squared'],
    difficulty: 2,
    tags: ['visual'],
  },
  {
    id: 'mlr-005',
    mode: 'gate-mcq',
    prompt: 'A student forgets to include the bias column of 1s in the design matrix X. What is the consequence?',
    options: [
      'The model becomes more accurate because there are fewer parameters to estimate',
      'The fitted hyperplane is forced through the origin — systematically wrong if the true intercept b ≠ 0',
      'XᵀX becomes invertible in cases where it previously was not',
      'Nothing — the bias term is optional in multiple linear regression',
    ],
    answer: 'B',
    explanation: 'Without the bias column, ŷ = Σ wⱼxⱼ only: the hyperplane must pass through the origin. If the true model has b ≠ 0, the fit is biased and typically worsens R². This is the classic "missing bias column" GATE trap.',
    trapExplanations: {
      A: 'Fewer parameters do not mean more accuracy — you lose the ability to model the intercept.',
      C: 'Dropping a column can only make rank deficiency WORSE or equal, never better.',
      D: 'The bias is structurally necessary for an affine (not purely linear) model.',
    },
    concepts: ['multiple-linear-regression', 'bias column', 'design matrix'],
    difficulty: 3,
    tags: ['trap'],
  },
  {
    id: 'mlr-006',
    mode: 'conceptual-mcq',
    prompt: 'With n = 10 samples and d = 50 features, what does the normal equation produce?',
    options: [
      'A unique solution, because there are more unknowns than equations is fine',
      'XᵀX is 51×51 but has rank ≤ 10 — singular, so infinitely many θ achieve zero training error',
      'A runtime error, because y has the wrong dimension',
      'The same solution as ridge regression with λ = 0',
    ],
    answer: 'B',
    explanation: 'The design matrix is 10×51 (bias included); its rank is at most 10 < 51, so XᵀX is singular. The normal equation has no unique solution — infinitely many θ interpolate the training data (zero training error) but generalize arbitrarily. This is the underdetermined regime.',
    trapExplanations: {
      A: 'More unknowns than equations means rank deficiency, not a bonus.',
      C: 'Dimensions are consistent; the problem is rank, not shape mismatch.',
      D: 'λ = 0 is the singular case; ridge needs λ > 0 to be invertible.',
    },
    concepts: ['multiple-linear-regression', 'underdetermined', 'normal equation'],
    difficulty: 3,
    tags: ['conceptual', 'trap'],
  },
];
