// src/topics/knn/questions.ts
import type { Question } from '../../engine/types';

export const knnQuestions: Question[] = [
  {
    id: 'knn-001',
    mode: 'nat',
    prompt: 'Training points: A(0,0) class 0, B(4,0) class 0, C(0,3) class 1, D(4,3) class 1. For the query Q(1,1) with k = 3 using Euclidean distance, what class is predicted? (Enter 0 or 1.)',
    answer: 0,
    tolerance: 0.01,
    explanation: 'Distances: d(Q,A) = √(1²+1²) = √2 ≈ 1.414, d(Q,C) = √(1²+2²) = √5 ≈ 2.236, d(Q,B) = √(3²+1²) = √10 ≈ 3.162, d(Q,D) = √(3²+2²) = √13 ≈ 3.606. The k=3 nearest are A (class 0), C (class 1), B (class 0) → votes 2 vs 1 → class 0.',
    concepts: ['knn', 'distance metrics', 'majority vote'],
    difficulty: 2,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'knn-002',
    mode: 'nat',
    prompt: 'Same points as knn-001: A(0,0) class 0, B(4,0) class 0, C(0,3) class 1, D(4,3) class 1. What is the MANHATTAN distance from query Q(1,1) to point D(4,3)? (Enter the number.)',
    answer: 5,
    tolerance: 0.01,
    explanation: 'Manhattan distance = |4−1| + |3−1| = 3 + 2 = 5. Under L1 the path along grid lines is longer than the Euclidean straight line (√13 ≈ 3.61) — the two metrics are not interchangeable.',
    concepts: ['knn', 'distance metrics', 'manhattan'],
    difficulty: 1,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'knn-003',
    mode: 'nat',
    prompt: 'Query Q(0,0), k = 2, Euclidean distance. Neighbors available: P1(1,0) class 0, P2(−1,0) class 1, P3(0,2) class 0, P4(0,−2) class 1. Both P1 and P2 are at distance 1 — the vote is a 1–1 tie. Which class is predicted under the nearest-of-tied rule (equal distance → lower class index)? (Enter 0 or 1.)',
    answer: 0,
    tolerance: 0.01,
    explanation: 'The two nearest are P1 (d=1, class 0) and P2 (d=1, class 1). Votes tie 1–1. Nearest-of-tied: both classes have their nearest neighbor at d=1, so the equal-distance rule applies → lower class index wins → class 0. A deterministic tie-break must exist for even k; relying on "random" or "first stored" is a trap.',
    concepts: ['knn', 'tie-breaking', 'majority vote'],
    difficulty: 3,
    tags: ['numerical', 'trap'],
  },
  {
    id: 'knn-004',
    mode: 'conceptual-mcq',
    prompt: 'Why does k = 1 overfit while a larger k generalizes better?',
    options: [
      'k = 1 lets a single noisy or outlier point decide the class; larger k averages over a neighborhood and smooths the boundary',
      'k = 1 always predicts the majority class of the whole dataset',
      'Larger k shrinks the training data so the model has fewer points to fit',
      'k = 1 has zero LOO error by construction',
    ],
    answer: 'A',
    explanation: 'With k=1 the decision boundary is the full Voronoi diagram — every training point owns its own region, so noise and outliers carve jagged cells. Larger k votes across a neighborhood, averaging out noise: region count drops from 51 (k=1) to 35 (k=15) in the simulation. This is the bias–variance dial of k-NN.',
    trapExplanations: {
      B: 'k = 1 follows the single nearest neighbor; predicting the global majority is what k → n does.',
      C: 'The dataset is never shrunk — k-NN stores everything (lazy learner).',
      D: 'The opposite: k=1 train error is 0, but LOO error is nonzero — that is exactly the overfitting signature.',
    },
    concepts: ['knn', 'overfitting', 'bias-variance'],
    difficulty: 2,
    tags: ['conceptual', 'trap'],
  },
  {
    id: 'knn-005',
    mode: 'visual',
    prompt: 'In the simulation, scrub the k slider from 1 to 15 (Euclidean, default seed) and watch the decision boundary and the region-count metric. What happens?',
    options: [
      'The boundary smooths and the region count decreases monotonically as k grows',
      'The boundary becomes more jagged and the region count increases',
      'The boundary does not change; only the query-point color changes',
      'The region count oscillates randomly because k-NN has no training phase',
    ],
    answer: 'A',
    explanation: 'k=1 draws the full Voronoi diagram (≈51 regions on the default seed); each step of the k-sweep widens the vote and merges cells, so the region count falls (≈35 at k=15). Scrubbing the run IS the boundary-smoothing animation. The distance rings around the query also grow as k widens.',
    trapExplanations: {
      B: 'Smoothing merges regions; jaggedness is the k=1 signature.',
      C: 'The boundary is exactly what changes.',
      D: 'The run is deterministic — same seed, same k, same boundary every time.',
    },
    concepts: ['knn', 'decision boundary', 'smoothing'],
    difficulty: 1,
    tags: ['visual'],
  },
  {
    id: 'knn-006',
    mode: 'gate-mcq',
    prompt: 'GATE-style: two features, height in cm (range 150–200) and income in ₹ (range 1–100 lakh). k-NN with Euclidean distance is run on the RAW features. Which statement is true?',
    options: [
      'Income dominates the distance because its numeric scale is far larger — the classifier effectively ignores height unless features are standardized',
      'The two features contribute equally because Euclidean distance squares both',
      'k must be odd to avoid ties regardless of the number of classes',
      'The metric choice (L1 vs L2) fixes the scaling problem automatically',
    ],
    answer: 'A',
    explanation: 'Euclidean distance sums squared differences: a 50-unit gap in income contributes 2500 while a 10-unit gap in height contributes 100 — the scale, not the importance, decides. Standardize (z-score) features first so every feature has equal influence. This is the classic "no feature scaling" trap.',
    trapExplanations: {
      B: 'Squaring amplifies the larger-scale feature even more — nothing is equalized.',
      C: 'Odd k only avoids ties for TWO classes; with 3+ classes ties can happen at any k and tie-break rules are still needed.',
      D: 'L1 is somewhat less sensitive but both metrics still mix raw units; scaling is the real fix.',
    },
    concepts: ['knn', 'feature scaling', 'normalization'],
    difficulty: 3,
    tags: ['trap', 'conceptual'],
  },
  {
    id: 'knn-007',
    mode: 'gate-mcq',
    prompt: 'Why does k-NN (and distance-based methods generally) degrade as the number of features d grows into the hundreds?',
    options: [
      'In high dimensions the volume concentrates near the surface of the space, so all points become nearly equidistant — the nearest neighbor is barely closer than the farthest (curse of dimensionality)',
      'Because k must be smaller than d for the vote to be defined',
      'Because Euclidean distance is undefined above d = 10',
      'Because the training phase becomes exponentially expensive',
    ],
    answer: 'A',
    explanation: 'In a d-dimensional unit cube, the inner (1−2ε) box holds only (1−2ε)^d of the volume — exponentially small. Distances concentrate: max/min distance ratios approach 1, so "nearest" stops meaning much. This indirect link to the curse of dimensionality is a favourite GATE framing.',
    trapExplanations: {
      B: 'k and d are independent; the vote needs k ≤ n, not k ≤ d.',
      C: 'Euclidean distance is defined in any dimension — it just becomes uninformative.',
      D: 'k-NN has NO training phase (lazy learner); the cost is per-query O(n·d), not training.',
    },
    concepts: ['knn', 'curse of dimensionality', 'high-dimensional data'],
    difficulty: 3,
    tags: ['indirect', 'conceptual'],
  },
  {
    id: 'knn-008',
    mode: 'conceptual-mcq',
    prompt: 'When would Manhattan (L1) distance be a better choice than Euclidean (L2) for k-NN?',
    options: [
      'When the features are heterogeneous and the axes are independently meaningful — L1 is more robust to a single outlying feature value',
      'When the classes are known to be separated by a straight line through the origin',
      'When k is odd',
      'Never — L2 is always at least as good as L1 for k-NN',
    ],
    answer: 'A',
    explanation: 'L1 sums absolute differences, so one extreme value on a single feature cannot dominate the total as strongly as the squared L2 term does (though scaling still matters). L2 is the default, but L1 is the robust choice for outlier-prone or axis-aligned data. The metric choice genuinely changes the Voronoi cells — the simulation demonstrates it.',
    trapExplanations: {
      B: 'Boundary linearity depends on the classifier geometry, not the metric choice alone.',
      C: 'k parity is about tie-breaking, unrelated to metric choice.',
      D: 'The metric changes the geometry (diamond vs circle iso-distance); "always" is never safe.',
    },
    concepts: ['knn', 'distance metrics', 'robustness'],
    difficulty: 2,
    tags: ['conceptual'],
  },
];
