// src/topics/pca-svd/questions.ts
// Measured anchors referenced below (n 40, corr 0.7, rotDeg 30, noise 0.15,
// seed 42 — the default run):
//   σ₁ = 8.804484511776364, σ₂ = 3.3373516320652685, λ(XᵀX) = 77.51894751810988,
//   λ(cov) = 1.9379736879527472, ratio = 2.6382, V₁ at 76.41°,
//   errFroK1 = 3.3374 = σ₂, errMseK1 = 0.2784 = σ₂²/n, baseline ‖X‖²_F/n = 2.2164.
import type { Question } from '../../engine/types';

export const svdQuestions: Question[] = [
  {
    id: 'svd-001',
    mode: 'nat',
    prompt: 'A matrix X has SVD with singular values σ₁ = 5 and σ₂ = 1. What is ‖X − X̂₁‖_F — the Frobenius norm of the best rank-1 approximation error? (Enter the number.)',
    answer: 1,
    tolerance: 0.01,
    explanation: 'By Eckart–Young the rank-k approximation error is the sum of the DROPPED singular values: in 2D, ‖X − X̂₁‖_F = √(σ₂²) = σ₂ = 1 (and the spectral norm is also σ₂ = 1). What you keep (σ₁) never enters the error — only what you drop does.',
    concepts: ['svd', 'eckart-young', 'low-rank approximation'],
    difficulty: 2,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'svd-002',
    mode: 'nat',
    prompt: 'The Gram matrix of a dataset is XᵀX with eigenvalues λ₁ = 81 and λ₂ = 9. What is the SECOND singular value σ₂? (Enter the number.)',
    answer: 3,
    tolerance: 0.01,
    explanation: 'σ_k = √λ_k(XᵀX). So σ₂ = √9 = 3 (and σ₁ = √81 = 9). The singular values are the SQUARE ROOTS of the Gram eigenvalues — a common GATE trap is reporting the eigenvalue itself (9) instead of its root (3).',
    concepts: ['svd', 'singular value', 'gram matrix'],
    difficulty: 1,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'svd-003',
    mode: 'nat',
    prompt: 'On the default run, σ₂ = 3.3374 and n = 40. What is the mean squared reconstruction error with rank k = 1? (Enter the number; it equals σ₂²/n.)',
    answer: 0.2784,
    tolerance: 0.005,
    explanation: 'MSE₁ = (1/n)‖X − X̂₁‖²_F = σ₂²/n = 3.3373516320652685²/40 = 0.278447897901218. This is the loss-curve metric (reconstructionError): with k = 1 the per-sample error equals the dropped energy σ₂²/n, and with k = 2 it is exactly 0 (measured 4.1e-32).',
    concepts: ['svd', 'reconstruction', 'eckart-young'],
    difficulty: 2,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'svd-004',
    mode: 'matrix',
    prompt: 'Match each factor of the economy SVD X = U_kΣ_kV_kᵀ to its correct meaning and dimension.',
    options: [
      'U_k',
      'Σ_k',
      'V_kᵀ',
      'X̂_k = U_kΣ_kV_kᵀ',
    ],
    answer: [
      'left singular vectors — per-point coefficients (scores), n × k',
      'diagonal of the top-k singular values, k × k',
      'right singular vectors transposed — the top-k feature directions (PCs), k × d',
      'the rank-k truncated-SVD reconstruction of the data, n × d',
    ],
    explanation: 'The economy SVD drops the zero rows/columns: U_k keeps the first k left singular vectors (n × k, one coefficient per point), Σ_k the k×k diagonal of the top-k σ\'s, and V_kᵀ the first k rows of Vᵀ (k × d, the feature directions). The product U_kΣ_kV_kᵀ is n × d and is exactly the best rank-k approximation (Eckart–Young). On the default run k = 1 gives U₁ (40×1), Σ₁ (1×1), V₁ᵀ (1×2); k = 2 gives U₂ (40×2), Σ₂ (2×2), V₂ᵀ (2×2).',
    concepts: ['svd', 'economy svd', 'dimensions'],
    difficulty: 2,
    tags: ['matrix'],
  },
  {
    id: 'svd-005',
    mode: 'conceptual-mcq',
    prompt: 'Why is the SVD the numerically stable way to compute PCA directions, compared with forming the covariance and solving an eigen-problem directly?',
    options: [
      'The SVD works with σ₁/σ₂ (the condition number of X), while the covariance route squares it to (σ₁/σ₂)² — squaring amplifies near-degeneracy and loses digits',
      'The SVD ignores the data entirely and only uses the singular values, which are always exact integers',
      'The SVD is stable because U and V are always the identity matrix',
      'The SVD avoids all square roots, so no precision is ever lost',
    ],
    answer: 'A',
    explanation: 'The covariance eigen-route forms XᵀX first, whose condition number is (σ₁/σ₂)² — the SVD\'s own σ₁/σ₂ SQUARED. On the default run σ₁/σ₂ = 2.64 so the covariance has condition ≈ 6.96, but on near-degenerate data (σ₂ → 0) squaring can turn a workable ratio into a numerically singular matrix. The SVD never forms XᵀX: it factors X directly, keeping the smaller condition number and roughly twice the digits of accuracy (the covariance-route comparison).',
    trapExplanations: {
      B: 'The SVD uses the actual data matrix X; only in the covariance route does the data get "squared away" into a Gram matrix — and singular values are real numbers, not integers.',
      C: 'U and V are the rotations of the factorization, not identities — if they were identities the data would already be axis-aligned with no need for an SVD.',
      D: 'The SVD does take square roots (σ = √λ) and squares entries during the math — the stability gain is about NOT forming XᵀX, not about avoiding square roots.',
    },
    concepts: ['svd', 'numerical stability', 'condition number'],
    difficulty: 4,
    tags: ['conceptual'],
  },
  {
    id: 'svd-006',
    mode: 'conceptual-mcq',
    prompt: 'On the default run the two singular values are σ₁ = 8.8045 and σ₂ = 3.3374. Rank-1 reconstruction keeps ONLY σ₁u₁v₁ᵀ. What fraction of the total "energy" (σ₁² + σ₂²) is retained by the rank-1 picture?',
    options: [
      'σ₁²/(σ₁² + σ₂²) = 77.52/88.66 ≈ 87.4%',
      'σ₁/(σ₁ + σ₂) = 8.80/12.14 ≈ 72.5%',
      'σ₂²/(σ₁² + σ₂²) = 11.14/88.66 ≈ 12.6%',
      '100% — rank 1 always reconstructs the data exactly',
    ],
    answer: 'A',
    explanation: 'The energy of the j-th direction is σ_j² (the variance contribution): the retained fraction at rank k is Σ_{j≤k}σ_j² / Σ_j σ_j². Rank 1 keeps σ₁² = 77.519 of the total 88.657 — 87.4% — and the remaining 12.6% is exactly the dropped σ₂². This is the compression-vs-quality trade-off: one number per point instead of two, at the cost of the thin-direction detail (the eigenviewer\'s two energy bars show this split).',
    trapExplanations: {
      B: 'Energy is the SQUARED singular value — using σ directly (72.5%) understates the retained fraction because the contribution of a direction to the variance is σ², not σ.',
      C: 'σ₂²/(σ₁² + σ₂²) is the fraction LOST by rank 1, not the fraction retained.',
      D: 'Only rank k = d = 2 reconstructs exactly; rank 1 leaves the σ₂ layer out (measured error 0.2784 = σ₂²/n).',
    },
    concepts: ['svd', 'low-rank approximation', 'energy'],
    difficulty: 2,
    tags: ['visual'],
  },
  {
    id: 'svd-007',
    mode: 'gate-mcq',
    prompt: 'For a data matrix X (n × 2) with SVD X = UΣVᵀ, which statement about the factors is TRUE?',
    options: [
      'V holds the feature-space directions (the PCs) and U holds the per-point coefficients — the right singular vectors are the eigenvectors of XᵀX',
      'U holds the feature-space directions and V holds the per-point coefficients — V is the eigenvectors of XXᵀ',
      'U and V are both n × n and identical to each other for every matrix',
      'Σ contains the eigenvalues of X, not the singular values',
    ],
    answer: 'A',
    explanation: 'XᵀX = VΣ²Vᵀ is the eigen-decomposition of the Gram matrix: its eigenvectors ARE the right singular vectors V (feature directions, d × d), and its eigenvalues are σ². U (n × n) holds the per-point coefficients — the "scores". The left/right swap is the classic trap: V and U live in different spaces and answer different questions (directions vs scores).',
    trapExplanations: {
      B: 'This is the left/right confusion reversed: U is the per-POINT factor (n × n), V is the per-FEATURE factor (d × d); the eigenvectors of XXᵀ are the LEFT singular vectors.',
      C: 'U (n × n) and V (d × d) generally have different sizes and are unrelated — only in the square symmetric case do they coincide.',
      D: 'Σ holds the singular values σ_k = √λ_k(XᵀX); the eigenvalues of X itself are not even defined for rectangular X.',
    },
    concepts: ['svd', 'singular vectors', 'trap'],
    difficulty: 3,
    tags: ['trap'],
  },
  {
    id: 'svd-008',
    mode: 'conceptual-mcq',
    prompt: 'For OLS you want the least-squares solution of Xβ = y, but X is rectangular (n > d) or rank-deficient (σ₂ = 0). Why is the SVD-based pseudoinverse X⁺ = VΣ⁺Uᵀ the right tool?',
    options: [
      'It inverts each singular value separately (1/σ_j, with 0 for the zero ones), so it works even when XᵀX is singular and (XᵀX)⁻¹ does not exist',
      'It computes the exact inverse of X by transposing it, giving β = Xᵀy with no approximation',
      'It avoids the normal equation by replacing X with its covariance, which is always invertible',
      'It only applies to square matrices, so for rectangular X you must use the normal equation instead',
    ],
    answer: 'A',
    explanation: 'The normal-equation solution β = (XᵀX)⁻¹Xᵀy exists only when XᵀX is invertible — on rank-deficient X (σ₂ = 0, the collinear failure data) it does not. The pseudoinverse inverts each singular value separately and maps 1/0 → 0, so X⁺ = VΣ⁺Uᵀ is always defined and yields the minimum-norm least-squares solution. It is also numerically better even in the full-rank case: it never squares the condition number (the SVD comparison).',
    trapExplanations: {
      B: 'X is rectangular — no inverse exists; the pseudoinverse is a generalization, not the transpose, and β = X⁺y, not Xᵀy.',
      C: 'Forming the covariance is precisely the unstable route the pseudoinverse avoids, and a covariance can still be singular.',
      D: 'The pseudoinverse is MOST useful for rectangular and rank-deficient matrices; the normal equation is the one with the square-matrix requirement (XᵀX).',
    },
    concepts: ['svd', 'pseudoinverse', 'least squares', 'indirect'],
    difficulty: 4,
    tags: ['indirect'],
  },
];