// src/topics/decision-trees-regression/questions.ts
// GATE-style questions. Every NAT answer is hand-verifiable — the arithmetic
// is written out in the explanation. MCQ trap options all carry trapExplanations.
import type { Question } from '../../engine/types';

export const dtrQuestions: Question[] = [
  {
    id: 'dtr-001',
    mode: 'nat',
    prompt: 'A classification node contains 60 samples of class A and 40 of class B. What is its Gini impurity?',
    answer: 0.48,
    tolerance: 0.001,
    explanation: 'p_A = 60/100 = 0.6, p_B = 40/100 = 0.4. Gini G = 1 − (p_A² + p_B²) = 1 − (0.36 + 0.16) = 1 − 0.52 = 0.48. (A pure node would give 0; a 50/50 mix gives 0.5.)',
    concepts: ['gini-impurity', 'decision-trees'],
    difficulty: 2,
    tags: ['formula', 'numerical'],
  },
  {
    id: 'dtr-002',
    mode: 'nat',
    prompt: 'A regression tree splits the 4 points (x, y) = (1,2), (2,2), (3,6), (4,6) at threshold x < 2.5. What is the SSE reduction ΔSSE of this split?',
    answer: 16,
    tolerance: 0.001,
    explanation: 'Before: all 4 points in one node, mean ȳ = (2+2+6+6)/4 = 4, SSE = (2−4)² + (2−4)² + (6−4)² + (6−4)² = 4+4+4+4 = 16. After: left leaf {(1,2),(2,2)} has mean 2 and SSE = 0; right leaf {(3,6),(4,6)} has mean 6 and SSE = 0. ΔSSE = 16 − 0 = 16.',
    concepts: ['sse-reduction', 'regression-tree'],
    difficulty: 3,
    tags: ['formula', 'numerical'],
  },
  {
    id: 'dtr-003',
    mode: 'nat',
    prompt: 'A regression tree has two leaves: region {x < 0} predicts 1.5 and region {x ≥ 0} predicts −2.5. What does the tree predict at x = 3?',
    answer: -2.5,
    tolerance: 0.001,
    explanation: 'x = 3 falls in the second region (3 ≥ 0), so the prediction is that leaf\'s constant, −2.5. The tree does NOT interpolate or extend a trend — its prediction is the piecewise constant of the containing leaf.',
    concepts: ['leaf-mean', 'regression-tree'],
    difficulty: 2,
    tags: ['formula', 'numerical'],
  },
  {
    id: 'dtr-004',
    mode: 'nat',
    prompt: 'A regression leaf contains the targets y = {3, 5, 7}. What constant does the leaf predict?',
    answer: 5,
    tolerance: 0.001,
    explanation: 'The leaf value that minimizes SSE is the mean: (3 + 5 + 7)/3 = 15/3 = 5. SSE at c = 5 is (3−5)² + (5−5)² + (7−5)² = 4 + 0 + 4 = 8; any other constant is worse.',
    concepts: ['leaf-mean', 'regression-tree'],
    difficulty: 2,
    tags: ['formula', 'numerical'],
  },
  {
    id: 'dtr-005',
    mode: 'conceptual-mcq',
    prompt: 'A regression tree with max depth 1 is trained on a noisy dataset. Which statement is TRUE?',
    options: [
      'It fits a straight line through the points',
      'It predicts a single constant everywhere — the mean of the training targets',
      'It partitions the x-axis at one threshold and predicts two constants (one per side)',
      'It interpolates each training point exactly',
    ],
    answer: 'C',
    explanation: 'Max depth 1 allows exactly one binary split (two leaves): the tree picks the threshold with the largest SSE reduction and predicts the mean of each side — a two-constant step function. It cannot draw a line (A) or interpolate (D) because leaves store constants, and it is not a single constant (B) unless the data cannot be usefully split.',
    trapExplanations: {
      A: 'Leaves store the mean of their samples — there is no slope anywhere in a regression tree.',
      B: 'That is depth 0 (no split). Depth 1 adds one threshold, giving two constants.',
      D: 'Interpolating every point is what a fully grown (deep) tree with min_leaf = 1 does — depth 1 is far too shallow.',
    },
    concepts: ['regression-tree', 'leaf-mean', 'maxDepth'],
    difficulty: 2,
    tags: ['conceptual'],
  },
  {
    id: 'dtr-006',
    mode: 'gate-mcq',
    prompt: 'A student evaluates a regression tree with accuracy = 87% (labels predicted correctly after rounding predictions to the nearest integer). What is wrong with this evaluation?',
    options: [
      'Nothing — accuracy is the standard metric for regression',
      'Accuracy after rounding discards the magnitude of error: a prediction of 5.2 vs true 8.1 is a huge miss but rounds to 5 vs 8, "correct"; the tree was trained on SSE and should be scored with MSE/SSE',
      'Rounding is fine but accuracy should be computed on the training set only',
      'Accuracy is correct but the tree should predict the median instead of the mean',
    ],
    answer: 'B',
    explanation: 'Regression trees minimize squared error and should be evaluated with a continuous loss (MSE, SSE, MAE). Rounding targets to integers and counting "correct" bins throws away the magnitude of every residual — the honest signal that the model under- or over-predicts. Accuracy is a classification metric (the Gini/entropy family), not a regression one.',
    trapExplanations: {
      A: 'Accuracy is a classification metric; for regression it collapses a continuous error into a boolean.',
      C: 'Training-set accuracy is even more misleading — the tree minimizes training error by construction.',
      D: 'The median is a different estimator (robust to outliers), but it does not fix a fundamentally wrong metric choice.',
    },
    concepts: ['regression-tree', 'evaluation', 'sse'],
    difficulty: 3,
    tags: ['trap'],
  },
  {
    id: 'dtr-007',
    mode: 'conceptual-mcq',
    prompt: 'Which is a KEY difference between CART (regression tree) and ID3 (classification tree)?',
    options: [
      'ID3 allows multi-way splits on categorical features; CART only binary splits',
      'CART uses entropy while ID3 uses Gini impurity',
      'ID3 leaves store the mean of the targets',
      'CART cannot handle continuous features',
    ],
    answer: 'A',
    explanation: 'CART is fundamentally binary (every split has two children, even for categorical features); ID3 can make a multi-way split — one branch per categorical value. The split criteria also differ: CART uses Gini/SSE reduction, ID3 uses information gain from entropy (so B is inverted), ID3 leaves store the majority class not the mean (C), and CART is famous for handling continuous features via threshold splits (D is false).',
    trapExplanations: {
      B: 'Backwards: ID3 uses entropy / information gain; CART uses Gini impurity (classification) or SSE reduction (regression).',
      C: 'ID3 is a CLASSIFIER — its leaves store a class label, not a target mean.',
      D: 'Continuous features are CART\'s signature strength: it evaluates sorted midpoints as split candidates.',
    },
    concepts: ['CART', 'ID3', 'decision-trees'],
    difficulty: 3,
    tags: ['indirect'],
  },
  {
    id: 'dtr-008',
    mode: 'visual',
    prompt: 'In the simulation, fit the default noisy sine data with max depth 1, then 3, then 6 (min leaf 1). What do you see?',
    options: [
      'Depth 1 is a flat line missing the wave; depth 3 hugs the sine with a few steps; depth 6 is a jagged staircase that follows the noise — test error falls, bottoms out, then rises',
      'All depths give identical fits because the data is deterministic',
      'Depth 6 has the lowest test error because it minimizes training error',
      'Depth 1 wiggles through every point; depth 6 is the smoothest fit',
    ],
    answer: 'A',
    explanation: 'Depth 1 = one threshold → two constants (huge bias, the sine is invisible). Depth 3 = a handful of steps that approximate the wave (good trade-off). Depth 6 = many leaves, each fitting a tiny region of noise — the step function becomes jagged, train error collapses while test error climbs: the classic overfitting signature visible in the loss-curve.',
    trapExplanations: {
      B: 'The data is seeded and reproducible, but the FITS at different depths are genuinely different models.',
      C: 'Lowest TRAIN error ≠ best model — the whole point of the held-out test split is that it exposes overfitting.',
      D: 'Reversed: depth 1 is the smooth flat line; depth 6 is the jagged one.',
    },
    concepts: ['regression-tree', 'overfitting', 'visualization'],
    difficulty: 2,
    tags: ['visual'],
  },
];