// src/topics/ridge-regression/questions.ts
import type { Question } from '../../engine/types';

export const ridgeQuestions: Question[] = [
  {
    id: 'ridge-001',
    mode: 'nat',
    prompt: 'For the design matrix X = [[1, 1], [2, 1]] (one feature x, bias column last) and y = [3, 4], ridge regression with λ = 1 solves θ = (XᵀX + λI)⁻¹Xᵀy. What is the weight w on the feature x? (Enter to 2 decimals.)',
    answer: 1.333,
    tolerance: 0.05,
    explanation: 'XᵀX = [[5, 3], [3, 2]] and Xᵀy = [11, 7]. With λ = 1: XᵀX + λI = [[6, 3], [3, 3]], whose inverse is (1/9)·[[3, −3], [−3, 6]]. Then θ = (1/9)[[3,−3],[−3,6]]·[11,7] = (1/9)[33−21, −33+42] = (1/9)[12, 9] = [4/3, 1]. So w = 4/3 ≈ 1.333. Check via equations: 3w + 3b = 7 and 6w + 3b = 11 ⇒ w = 4/3 ✓. Note the contrast: OLS (λ=0) gives w = 1, b = 2 — the penalty moved both.',
    concepts: ['ridge-regression', 'closed form', 'matrix operations'],
    difficulty: 4,
    tags: ['matrix', 'numerical', 'formula'],
  },
  {
    id: 'ridge-002',
    mode: 'conceptual-mcq',
    prompt: 'Why does ridge regression with finite λ > 0 never produce exact zero coefficients, while lasso does?',
    options: [
      'Because the L2 penalty is differentiable everywhere with gradient 2λθ that vanishes at θ = 0 — the optimum stays at an interior point unless the data gradient already vanishes there',
      'Because ridge only shrinks the largest coefficient and leaves small ones untouched',
      'Because λI makes the Hessian XᵀX + λI diagonal, which disables feature selection',
      'Because ridge uses matrix inversion instead of an iterative solver',
    ],
    answer: 'A',
    explanation: 'The L2 penalty is smooth: ∂(λ‖θ‖²)/∂θ = 2λθ → 0 as θ → 0. A coefficient can sit at exactly zero only if the unpenalized gradient is also zero there — generically false. Lasso’s L1 penalty |θ| has a kink at 0 whose subgradient interval [−λ, λ] makes zero a valid optimum, which is what creates sparsity.',
    trapExplanations: {
      B: 'Ridge shrinks ALL coefficients, proportionally to their magnitude in each eigen-direction.',
      C: 'XᵀX + λI is not diagonal — λI only shifts the eigenvalues.',
      D: 'The solver is irrelevant; the property is structural to the L2 penalty.',
    },
    concepts: ['ridge-regression', 'lasso-regression', 'sparsity'],
    difficulty: 3,
    tags: ['conceptual', 'trap'],
  },
  {
    id: 'ridge-003',
    mode: 'visual',
    prompt: 'In the simulation, scrub the λ slider from 0 to 10 and watch the fitted coefficients and the ‖θ‖ metric. Which statement best describes what you observe?',
    options: [
      'Every coefficient shrinks monotonically toward 0 — ‖θ‖ decreases steadily as λ grows',
      'Only the largest coefficient shrinks; the small ones grow to compensate',
      'The coefficients oscillate around the OLS solution without a clear trend',
      'The coefficients grow without bound because λ inflates the design matrix',
    ],
    answer: 'A',
    explanation: 'The shrinkage path: each snapshot is the ridge fit at its λ, and ‖θ(λ)‖ = ‖(XᵀX + λI)⁻¹Xᵀy‖ is provably non-increasing in λ. All coefficients move toward 0 (the bias column included), and the norm falls monotonically.',
    trapExplanations: {
      B: 'Shrinkage is proportional per eigen-direction — no coefficient grows to compensate.',
      C: 'The path is deterministic and monotone in norm, not oscillatory.',
      D: 'λ adds a positive term to the diagonal, which SHRINKS the solution — the inverse gets smaller, not larger.',
    },
    concepts: ['ridge-regression', 'shrinkage path'],
    difficulty: 2,
    tags: ['visual'],
  },
  {
    id: 'ridge-004',
    mode: 'gate-mcq',
    prompt: 'Ridge regression with λ = 0 is mathematically identical to:',
    options: [
      'Ordinary least squares via the normal equation — the penalty term vanishes and θ = (XᵀX)⁻¹Xᵀy',
      'A model whose coefficients are all exactly zero',
      'Ridge regression with λ = ∞',
      'A model that always predicts the mean of the training targets',
    ],
    answer: 'A',
    explanation: 'Setting λ = 0 in J = MSE + λ‖θ‖² removes the penalty; the closed form (XᵀX + 0·I)⁻¹Xᵀy = (XᵀX)⁻¹Xᵀy is exactly OLS. This is the classic trap: "ridge at λ=0" is NOT a zero model — it is plain least squares.',
    trapExplanations: {
      B: 'A zero-coefficient model is what λ → ∞ approaches, not λ = 0.',
      C: 'λ = ∞ is the opposite end of the path.',
      D: 'Predicting the mean is a constant model — unrelated to the ridge path.',
    },
    concepts: ['ridge-regression', 'ordinary least squares', 'normal equation'],
    difficulty: 2,
    tags: ['trap'],
  },
  {
    id: 'ridge-005',
    mode: 'gate-mcq',
    prompt: 'GATE-style statement: "Ridge regression can drive some coefficients exactly to zero, giving automatic feature selection." Is this statement true or false, and why?',
    options: [
      'False — ridge shrinks all coefficients proportionally but never exactly zeroes any for finite λ; sparsity is lasso’s feature',
      'True — the L2 penalty is a sparsity inducer like the L1 penalty',
      'True, but only when the features are perfectly collinear',
      'False — ridge does not change the coefficients at all',
    ],
    answer: 'A',
    explanation: 'The L2 penalty is smooth everywhere, so the optimum is interior — no coefficient lands on exactly zero unless the data forces it. Lasso’s L1 penalty has a kink at 0 (subgradient contains 0) which is what produces exact zeros and feature selection. This ridge-vs-lasso sparsity contrast is a frequent GATE question.',
    trapExplanations: {
      B: 'L2 does not induce sparsity; L1 does.',
      C: 'Collinearity worsens OLS but does not make ridge produce zeros.',
      D: 'Ridge definitely changes coefficients — that is its whole point.',
    },
    concepts: ['ridge-regression', 'lasso-regression', 'sparsity'],
    difficulty: 3,
    tags: ['trap', 'conceptual'],
  },
  {
    id: 'ridge-006',
    mode: 'conceptual-mcq',
    prompt: 'Why does XᵀX + λI (with λ > 0) always have an inverse, even when XᵀX is singular because the features are collinear?',
    options: [
      'XᵀX is positive semi-definite, so every eigenvalue μ ≥ 0; adding λI shifts every eigenvalue to μ + λ ≥ λ > 0, making the matrix positive definite',
      'Because λI replaces XᵀX entirely',
      'Because ridge runs gradient descent instead of inverting a matrix',
      'It does not — collinearity breaks ridge exactly the same way it breaks OLS',
    ],
    answer: 'A',
    explanation: 'XᵀX is always symmetric positive semi-definite: its eigenvalues are ≥ 0. Adding λ to every diagonal entry adds λ to every eigenvalue (the identity is diagonal in every basis), so the regularized Gram has all eigenvalues ≥ λ > 0 and is invertible. This is exactly why ridge "fixes" collinearity.',
    trapExplanations: {
      B: 'λI is added to XᵀX, not a replacement.',
      C: 'The closed form still inverts (XᵀX + λI); no gradient descent is needed.',
      D: 'Restoring invertibility is ridge’s defining property — the drift note in the plan calls this the "forgetting +λI" mistake.',
    },
    concepts: ['ridge-regression', 'matrix inverse', 'eigenvalues'],
    difficulty: 3,
    tags: ['conceptual', 'matrix'],
  },
  {
    id: 'ridge-007',
    mode: 'matrix',
    prompt: 'The design matrix X is n × (d+1) (bias column last). What are the dimensions of XᵀX + λI?',
    options: ['(d+1) × (d+1)', 'n × n', 'n × (d+1)', '(d+1) × n'],
    answer: 'A',
    explanation: 'XᵀX is the product of (d+1)×n with n×(d+1), so it is (d+1)×(d+1). Adding λI (the identity of the same size) keeps it (d+1)×(d+1). The sample count n cancels in the product — the Gram matrix is always square, sized by the parameter count.',
    trapExplanations: {
      B: 'n × n would be XXᵀ, the sample-space Gram matrix.',
      C: 'XᵀX is square — the outer product of the parameter dimension.',
      D: 'XᵀX is not transposed: Xᵀ is on the left, so the result is (d+1)×(d+1).',
    },
    concepts: ['ridge-regression', 'matrix dimensions'],
    difficulty: 2,
    tags: ['matrix'],
  },
  {
    id: 'ridge-008',
    mode: 'nat',
    prompt: 'Reuse the problem of ridge-001: X = [[1, 1], [2, 1]], y = [3, 4], λ = 1. Compute θ = (XᵀX + λI)⁻¹Xᵀy. What is the intercept b? (Enter to 2 decimals.)',
    answer: 1,
    tolerance: 0.05,
    explanation: 'From the worked solution of ridge-001: XᵀX = [[5,3],[3,2]], Xᵀy = [11,7], XᵀX + λI = [[6,3],[3,3]], and θ = (1/9)·[[3,−3],[−3,6]]·[11,7] = [4/3, 1]. The intercept is b = 1. Check: with w = 4/3, equation 3w + 3b = 7 gives 4 + 3b = 7 ⇒ b = 1 ✓. Notice OLS gave b = 2 — the L2 penalty shrank the intercept too.',
    concepts: ['ridge-regression', 'closed form', 'matrix operations'],
    difficulty: 3,
    tags: ['matrix', 'numerical', 'formula'],
  },
];
