// src/topics/pca/questions.ts
// Measured anchors referenced below (n 40, corr 0.7, rotDeg 30, noise 0.15,
// seed 42 — the default run):
//   Σ = [[0.3701, 0.3791],[0.3791, 1.8463]], λ₁ = 1.9379736879527472,
//   λ₂ = 0.2784478979012177, total = 2.216421585853965, ratio₁ = 0.8744,
//   ratio₂ = 0.1256, PC1 = (0.2350, 0.9720) at θ₁ = 76.41°,
//   reconErrK1 = 0.2784 (= λ₂), reconErrK2 = 0.
//   Centering contrast (rotDeg 80): centered PC1 at 127.15° vs RAW at 33.30°.
import type { Question } from '../../engine/types';

export const pcaQuestions: Question[] = [
  {
    id: 'pca-001',
    mode: 'nat',
    prompt: 'The centered covariance of a dataset is Σ = [[2, 1],[1, 2]]. Find the LARGEST eigenvalue of Σ. (Enter the number.)',
    answer: 3,
    tolerance: 0.01,
    explanation: 'Characteristic polynomial: det(Σ − λI) = (2−λ)² − 1² = 0 ⇒ λ² − 4λ + 3 = 0 ⇒ λ = 1, 3. The eigenvalues are 3 and 1, so the largest is 3. The largest eigenvalue λ₁ is the variance of the data along the first principal component — for [[2,1],[1,2]] that direction is (1,1)/√2 with variance 3.',
    concepts: ['pca', 'eigenvalue', 'characteristic polynomial'],
    difficulty: 2,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'pca-002',
    mode: 'nat',
    prompt: 'On the default run the eigenvalues are λ₁ = 1.9380 and λ₂ = 0.2784. What fraction of the total variance does PC1 explain? (Enter a number between 0 and 1.)',
    answer: 0.8744,
    tolerance: 0.005,
    explanation: 'explained ratio₁ = λ₁/(λ₁ + λ₂) = 1.9379736879527472/2.216421585853965 = 0.87437. Total variance is the trace of Σ, invariant under rotation — the two eigenvalues partition it, and PC1 (the max-variance direction) alone captures 87.4%.',
    concepts: ['pca', 'explained variance'],
    difficulty: 1,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'pca-003',
    mode: 'nat',
    prompt: 'Keeping only PC1 on the default run loses the variance along PC2. What is the mean squared reconstruction error with k = 1? (Enter the number; it equals the dropped eigenvalue.)',
    answer: 0.2784,
    tolerance: 0.005,
    explanation: 'error₁ = Σ_{j>1} λ_j = λ₂ = 0.2784478979012177. Projecting onto PC1 and back leaves exactly the PC2 component per point; its average squared length is the variance along v₂, which IS λ₂ (verified to 1e-12 by the tests). With k = 2 the reconstruction is lossless (error 0).',
    concepts: ['pca', 'reconstruction', 'eigenvalue'],
    difficulty: 2,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'pca-004',
    mode: 'conceptual-mcq',
    prompt: 'Why does maximizing the projected variance uᵀΣu over unit directions u lead to the EIGENVECTORS of Σ?',
    options: [
      'The Rayleigh quotient R(u) = uᵀΣu/uᵀu is stationary exactly at the eigenvectors, and with ‖u‖ = 1 its maximum is the largest eigenvalue λ₁ at u = v₁',
      'Eigenvectors are the only unit vectors that exist for a symmetric matrix, so the maximum must land on one',
      'Because Σ is invertible, its eigenvectors are the coordinate axes of the data space',
      'Maximizing variance is equivalent to minimizing ‖u‖, which forces u onto the eigenvectors',
    ],
    answer: 'A',
    explanation: 'The Lagrange-multiplier derivation (derivation pca-maximize-lagrange): maximize uᵀΣu s.t. uᵀu = 1. Stationarity gives 2Σu − 2λu = 0 ⇒ Σu = λu — the eigen-equation. So the critical directions of the Rayleigh quotient ARE the eigenvectors, and the eigenvalue λ equals the achieved variance. On the default run the sweep curve peaks at 76.4° with uᵀΣu = 1.9380 = λ₁ — the exact closed-form solution lands on the peak.',
    trapExplanations: {
      B: 'Symmetric matrices have many unit vectors; eigenvectors are special precisely because they make uᵀΣu stationary — not because they are the only unit vectors.',
      C: 'Invertibility is irrelevant to the eigen-directions, and eigenvectors are NOT the coordinate axes in general — here the PCs sit at 76.4°, not along x or y.',
      D: 'The constraint is ‖u‖ = 1 (fixed norm), not minimizing the norm — and the optimum follows from stationarity of the quotient, not from norm minimization.',
    },
    concepts: ['pca', 'rayleigh quotient', 'eigenvector', 'optimization'],
    difficulty: 3,
    tags: ['conceptual'],
  },
  {
    id: 'pca-005',
    mode: 'matrix',
    prompt: 'Match each PCA quantity to its meaning.',
    options: [
      'Σ = (1/n)X_cᵀX_c',
      'λ_k',
      'v_k',
      'z_i = v_k·(x_i − μ)',
    ],
    answer: [
      'the centered covariance matrix — encodes the spread and correlation of the cloud',
      'the variance of the data along PC k (the eigenvalue)',
      'the k-th principal direction — a unit eigenvector of Σ',
      'the score of point i on PC k — its signed coordinate along the principal axis',
    ],
    explanation: 'The pipeline: center the data → form Σ = (1/n)X_cᵀX_c → eigen-decompose Σv = λv → project z_i = v_k·(x_i − μ). On the default run Σ = [[0.3701, 0.3791],[0.3791, 1.8463]] has eigenvalues λ₁ = 1.9380, λ₂ = 0.2784 with v₁ = (0.2350, 0.9720) — the matrix view of the final snapshot shows exactly these pieces (Σ, λ, V, reconstruction error).',
    concepts: ['pca', 'covariance', 'projection', 'linear algebra'],
    difficulty: 2,
    tags: ['matrix'],
  },
  {
    id: 'pca-006',
    mode: 'visual',
    prompt: 'Run the default simulation (n 40, corr 0.7, rotDeg 30, noise 0.15, seed 42) and scrub to the final snapshot. Which direction is PC1, and why?',
    options: [
      'PC1 points up-right at θ₁ ≈ 76.4° = (0.235, 0.972) — the cloud is stretched mostly vertically (Σ₂₂ = 1.8463 > Σ₁₁ = 0.3701), and PC1 is the direction of MAXIMUM projected variance',
      'PC1 points along the x-axis at 0° because the sweep starts at θ = 0°',
      'PC1 points toward the data mean μ = (2.51, 1.62) because the cloud is centered there',
      'PC1 points along the y-axis at exactly 90° because y has the larger variance',
    ],
    answer: 'A',
    explanation: 'Scrub the run: the variance curve (loss view) rises from R(0°) = 0.3701 (x-variance) to its peak at θ₁ = 76.4° — the closed-form final lands on the peak with λ₁ = 1.9380. The cloud spreads more along y than x, and the positive covariance (0.3791) tilts the major axis up-right rather than straight up. PC1 is the direction of maximum projected variance — NOT the mean direction, NOT an axis.',
    trapExplanations: {
      B: 'The sweep starts at 0° but keeps rotating until the variance curve peaks at 76.4° — the final snapshot is the closed-form optimum, not the initial axis.',
      C: 'The mean μ = (2.51, 1.62) is where the cloud is CENTERED, not a direction of spread. Projections are measured around μ; the mean direction is only the uncentered (wrong) PC1.',
      D: 'The y-axis has larger variance, but the positive covariance couples the axes — the max-variance direction is tilted up-right at 76.4°, not straight up.',
    },
    concepts: ['pca', 'principal component', 'visualization', 'variance'],
    difficulty: 2,
    tags: ['visual'],
  },
  {
    id: 'pca-007',
    mode: 'conceptual-mcq',
    prompt: 'On the rotDeg-80 config, the CENTERED covariance gives PC1 at 127.15°, but the RAW (uncentered) covariance (1/n)Σᵢ xᵢxᵢᵀ gives PC1 at 33.30°. Why does forgetting to center break PCA so badly?',
    options: [
      'The raw matrix is Σ + μμᵀ (the mean-offset term): with μ = (2.38, 1.61) the offset term ‖μ‖² ≈ 8.3 dominates the spread (total ≈ 2.19), so the raw PC1 points at the MEAN — the direction of the offset, not of the variance',
      'Centering only moves the origin, and PCA directions are invariant to translations, so the two answers should be identical',
      'The raw covariance is not symmetric, so its eigenvectors are meaningless',
      'Uncentered PCA accidentally uses the class labels, which changes the covariance',
    ],
    answer: 'A',
    explanation: '(1/n)XᵀX = (1/n)Σᵢ (xᵢ−μ)(xᵢ−μ)ᵀ + μμᵀ = Σ + μμᵀ. The rank-1 offset μμᵀ has eigenvalue ‖μ‖² — for the rotDeg-80 draw the mean is (2.384, 1.612), so ‖μ‖² ≈ 8.28 and the raw matrix\'s dominant eigenvalue measures 8.556, roughly four times the total data variance (2.186) — so the dominant eigenvector of the raw matrix points along μ (raw PC1 measured at 33.30°, mean direction 34.06°). Centered PCA finds the real structure at 127.15°. Measured consequence: the raw PC1 explains only 12.6% of the CENTERED variance.',
    trapExplanations: {
      B: 'PCA is NOT translation-invariant without an explicit centering step: the raw second-moment matrix includes the μμᵀ term, which rotates every PC. You must subtract the mean FIRST.',
      C: 'The raw second-moment matrix IS symmetric (xᵢxᵢᵀ summed is symmetric); the problem is the offset term, not symmetry.',
      D: 'PCA is unsupervised — no labels anywhere. The failure is purely from the missing centering step.',
    },
    concepts: ['pca', 'centering', 'covariance', 'trap'],
    difficulty: 3,
    tags: ['trap', 'conceptual'],
  },
  {
    id: 'pca-008',
    mode: 'gate-mcq',
    prompt: 'GATE-style: the eigenvalues of the centered covariance are λ₁ = 1.9380 and λ₂ = 0.2784 (sorted descending). A student mistakenly swaps them and takes PC1 to be the eigenvector of λ₂. What goes wrong?',
    options: [
      'The chosen axis is the MINIMUM-variance direction: it captures only 12.6% of the variance, so it is the worst single-direction representation, and the explained-variance ratio is inverted',
      'Nothing: eigenvectors are all equivalent in PCA, and the explained variance is unaffected by which is called PC1',
      'The swap makes the eigenvectors non-orthogonal, so the reconstruction is no longer exact',
      'Swapping eigenvalues changes the data itself, so all projections become complex-valued',
    ],
    answer: 'A',
    explanation: 'PCA REQUIRES descending order: PC1 = argmax variance = eigenvector of the LARGEST eigenvalue. Using λ₂\'s eigenvector as PC1 selects the direction of least spread — on the default run that is 76.4° + 90° = 166.4° with only 12.6% of the variance (the eigenviewer\'s bars would show the thin direction as "first"). The reconstruction error would then be λ₁ = 1.9380 instead of λ₂ = 0.2784 — a 7× worse loss.',
    trapExplanations: {
      B: 'Eigenvectors are NOT interchangeable in PCA: the whole point is ordering by explained variance, and the top-k choice depends on that order.',
      C: 'Orthogonality comes from symmetry of Σ, independent of the ordering — the swapped frame is still orthogonal.',
      D: 'Eigenvalues of a symmetric matrix are real; swapping labels changes nothing about the data or the numbers, only which direction you treat as primary.',
    },
    concepts: ['pca', 'eigenvalue ordering', 'explained variance'],
    difficulty: 2,
    tags: ['trap', 'conceptual'],
  },
  {
    id: 'pca-009',
    mode: 'gate-mcq',
    prompt: 'GATE-style: how are PCA and the SVD of the centered data matrix X_c related?',
    options: [
      'X_c = UΣVᵀ with PCs = the right singular vectors V; the covariance eigen-values are λ_k = σ_k²/n (squared singular values scaled by 1/n)',
      'PCA and SVD are unrelated: SVD is for square matrices only, while PCA works on any data',
      'The PCs are the left singular vectors U, and λ_k = σ_k directly',
      'SVD gives the same PCs but only when the data is already centered and scaled to unit variance',
    ],
    answer: 'A',
    explanation: 'From X_c = UΣVᵀ, the covariance is (1/n)X_cᵀX_c = V(Σ²/n)Vᵀ — an eigen-decomposition with eigenvectors V (right singular vectors) and eigenvalues σ_k²/n. So computing PCA by eigen-decomposition of the covariance and computing the SVD of X_c are THE SAME computation (the pca-svd topic builds on this). On the default run λ₁ = 1.9380 = σ₁²/40, λ₂ = 0.2784 = σ₂²/40.',
    trapExplanations: {
      B: 'SVD exists for ANY matrix, rectangular included — X_c is n×2 here. PCA is precisely the SVD of the centered data matrix.',
      C: 'U holds the SCORES (per-point coordinates in the PC frame); the DIRECTIONS are V. And the link is λ = σ²/n, not σ.',
      D: 'Standardization is a separate preprocessing choice; the SVD link holds for any centered X_c, scaled or not.',
    },
    concepts: ['pca', 'svd', 'singular value', 'indirect'],
    difficulty: 3,
    tags: ['trap', 'indirect'],
  },
];