// src/topics/softmax-regression/questions.ts
import type { Question } from '../../engine/types';

export const softmaxQuestions: Question[] = [
  {
    id: 'softmax-001',
    mode: 'nat',
    prompt: 'For logits z = [1, 2, 3] (three classes), compute the softmax probability of class 3: ŷ₃ = e³ / (e¹ + e² + e³). Enter your answer to 3 decimals.',
    answer: 0.665,
    tolerance: 0.005,
    explanation: 'e¹ = 2.71828, e² = 7.38906, e³ = 20.08554. Denominator = 2.71828 + 7.38906 + 20.08554 = 30.19288. ŷ₃ = 20.08554 / 30.19288 = 0.66524 ≈ 0.665. Sanity check: ŷ₁ = 0.09003, ŷ₂ = 0.24473, and 0.09003 + 0.24473 + 0.66524 = 1.00000 — the outputs sum to 1.',
    concepts: ['softmax', 'probability'],
    difficulty: 3,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'softmax-002',
    mode: 'nat',
    prompt: 'For logits z = [0, 1, 0] (three classes), compute ŷ₂ — the softmax probability of the MIDDLE class (index 1, logit = 1). Enter your answer to 3 decimals.',
    answer: 0.576,
    tolerance: 0.005,
    explanation: 'e⁰ = 1, e¹ = 2.71828, e⁰ = 1. Denominator = 1 + 2.71828 + 1 = 4.71828. ŷ₂ = 2.71828 / 4.71828 = 0.57612 ≈ 0.576. Each of the two logit-0 classes gets 1/4.71828 = 0.21194; the three probabilities sum to 0.57612 + 0.21194 + 0.21194 = 1.00000.',
    concepts: ['softmax', 'probability'],
    difficulty: 2,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'softmax-003',
    mode: 'conceptual-mcq',
    prompt: 'Why does the softmax use exponentiation rather than, say, the raw scores or a linear normalization?',
    options: [
      'exp is strictly monotone (so argmax is preserved) and strictly positive (so the output is always a valid probability), and it makes the model a smooth differentiable surrogate of the argmax',
      'exp keeps the outputs bounded in [0, 1] only for small scores',
      'exp is used because it makes the outputs sum to exactly zero',
      'exp compresses large scores so the decision boundary becomes non-linear',
    ],
    answer: 'A',
    explanation: 'Two properties of exp do the work: monotonicity (largest score → largest probability, so the class ranking is unchanged) and positivity (every output is > 0, so the normalized vector is a genuine probability distribution). The smoothness gives gradient descent a differentiable target — the "soft" argmax.',
    trapExplanations: {
      B: 'The [0, 1] range comes from NORMALIZATION by the sum, not from exp itself — exp outputs can be arbitrarily large.',
      C: 'Outputs sum to 1, not 0.',
      D: 'The decision boundary stays LINEAR (z_k = z_j); exp is a monotone transform and does not curve it.',
    },
    concepts: ['softmax', 'activation function'],
    difficulty: 2,
    tags: ['conceptual'],
  },
  {
    id: 'softmax-004',
    mode: 'matrix',
    prompt: 'The model uses logits z = W·x + b with a weight matrix W (K×d), feature vector x (d×1) and bias b (K×1). What is the dimension of the logit vector z?',
    options: ['K × 1', 'd × 1', 'K × d', 'n × 1'],
    answer: 'A',
    explanation: '(K×d)·(d×1) = (K×1), and adding the (K×1) bias keeps it (K×1): one logit per class. This is the standard softmax parameterization — W has one row per class (rows = classes), so matrix-animator shows W as a K×d matrix animating per epoch.',
    trapExplanations: {
      B: 'd × 1 is the FEATURE vector x, not the logits.',
      C: 'K × d is the weight matrix W itself.',
      D: 'n × 1 would be the per-point batch, but z is computed per point.',
    },
    concepts: ['softmax', 'matrix dimensions'],
    difficulty: 2,
    tags: ['matrix'],
  },
  {
    id: 'softmax-005',
    mode: 'visual',
    prompt: 'In the simulation (margin = 3, trained model), the decision boundary between class 1 and class 2 is the set of points where ŷ₁ = ŷ₂. What shape is that boundary, and where does it sit relative to the two clusters?',
    options: [
      'A straight line through the midpoint of the two cluster centers — the logits z₁ and z₂ are both linear, so ŷ₁ = ŷ₂ ⟺ z₁ = z₂ is a line',
      'A curved arc that wraps around both clusters',
      'A closed circle surrounding the smaller cluster',
      'A vertical line through the origin regardless of the cluster positions',
    ],
    answer: 'A',
    explanation: 'ŷ₁ = ŷ₂ ⟺ z₁ = z₂ ⟺ (w₁ − w₂)·x + (b₁ − b₂) = 0 — a linear equation in x, hence a straight line. With roughly symmetric Gaussian clusters it passes between their centers; where clusters overlap, points on the wrong side are misclassified (visible when margin is small).',
    trapExplanations: {
      B: 'All decision boundaries of linear classifiers are straight; curvature needs a kernel or hidden layer.',
      C: 'Circles arise only with non-linear features or radial kernels.',
      D: 'The boundary passes through the midpoint of the two centers, which moves with the data — not fixed at the origin.',
    },
    concepts: ['softmax', 'decision boundary'],
    difficulty: 3,
    tags: ['visual'],
  },
  {
    id: 'softmax-006',
    mode: 'gate-mcq',
    prompt: 'A model computes softmax(z) with z = [1000, 1001, 1002] WITHOUT subtracting the max (no max-shift). What happens numerically, and what is the correct stable computation?',
    options: [
      'e^{1002} overflows double precision to Infinity → probabilities become NaN; the fix is to subtract the max logit m = 1002 first, which leaves exp(0), exp(−1), exp(−2) — finite and identical to the exact answer',
      'It works fine because exp is computed in log space',
      'The outputs underflow to exactly 0',
      'The argmax flips because the shift changes which class is most likely',
    ],
    answer: 'A',
    explanation: 'e^{1002} ≈ 10⁴³⁵ far exceeds the double maximum ≈ 1.8×10³⁰⁸, so the naive sum is Infinity and the division yields NaN. Subtracting m = 1002 (shift invariance — the probabilities are IDENTICAL) leaves e⁰, e⁻¹, e⁻² ≈ [1, 0.368, 0.135], sum 1.503 → ŷ ≈ [0.665, 0.245, 0.090]. This is the canonical softmax trap.',
    trapExplanations: {
      B: 'No hidden log-space computation happens — naive softmax exponentiates first.',
      C: 'Underflow (→ 0) happens for very NEGATIVE logits; huge POSITIVE logits overflow to Infinity.',
      D: 'exp is monotone, so subtracting a constant shifts all exponents equally and cannot change the argmax.',
    },
    concepts: ['softmax', 'numerical stability', 'log-sum-exp'],
    difficulty: 3,
    tags: ['trap', 'numerical'],
  },
  {
    id: 'softmax-007',
    mode: 'conceptual-mcq',
    prompt: 'For K = 2 classes, how does the softmax relate to the logistic sigmoid σ(z) = 1/(1 + e^{−z})?',
    options: [
      'Softmax with 2 classes equals the sigmoid of the logit DIFFERENCE: ŷ₁ = σ(z₁ − z₀) — softmax generalizes logistic regression',
      'Softmax with 2 classes is the sum of two independent sigmoids',
      'They are unrelated — sigmoid is for regression, softmax for classification',
      'Sigmoid is the derivative of the 2-class softmax',
    ],
    answer: 'A',
    explanation: 'Factor e^{z₀} out of ŷ₁ = e^{z₁}/(e^{z₀}+e^{z₁}): ŷ₁ = 1/(1 + e^{z₀−z₁}) = 1/(1 + e^{−(z₁−z₀)}) = σ(z₁ − z₀). Only the difference of the two logits matters (the shared shift cancels — shift invariance again). So logistic regression is exactly the K = 2 softmax; softmax is its multiclass generalization.',
    trapExplanations: {
      B: 'Two independent sigmoids would give probabilities that need not sum to 1; softmax guarantees Σŷ = 1 by construction.',
      C: 'Both are classification-output layers; the sigmoid is the binary special case of softmax.',
      D: 'The derivative of softmax is ŷ(δ − ŷᵀŷ), not the sigmoid.',
    },
    concepts: ['softmax', 'sigmoid', 'logistic regression'],
    difficulty: 3,
    tags: ['trap', 'conceptual'],
  },
  {
    id: 'softmax-008',
    mode: 'gate-mcq',
    prompt: 'The categorical cross-entropy loss is L = −Σᵢ log ŷ_{i, yᵢ}. The gradient of L with respect to the class-k weight vector is:',
    options: [
      '(1/n) Σᵢ (ŷ_{ik} − 1{yᵢ = k})·xᵢ — the softmax error times the feature vector',
      '(1/n) Σᵢ (yᵢ − ŷ_{ik})·xᵢ for every class k, including k ≠ yᵢ',
      '(1/n) Σᵢ ŷ_{ik}·xᵢ — the probability alone, without the indicator',
      '−Σᵢ 1{yᵢ = k}·xᵢ — only the true class contributes',
    ],
    answer: 'A',
    explanation: 'By the chain rule ∂L/∂z_{ik} = ŷ_{ik} − 1{yᵢ = k}, so ∂L/∂w_k = (1/n)Σᵢ(ŷ_{ik} − 1{yᵢ = k})·xᵢ. The indicator subtracts the one-hot truth: classes that should NOT own point i get pushed away (positive residual), the true class is pulled toward owning it (negative residual). This mirrors the famous (ŷ − y)x result of logistic regression.',
    trapExplanations: {
      B: 'yᵢ is a class INDEX, not a probability — yᵢ − ŷ_{ik} is dimensionally wrong; the correct form uses the one-hot indicator.',
      C: 'Without the −1{y = k} term every class gradient is positive — the model would push ALL class probabilities up and never specialize.',
      D: 'Only the true class term ignores the model prediction ŷ entirely — gradients would be independent of the current fit.',
    },
    concepts: ['softmax', 'cross-entropy', 'gradient'],
    difficulty: 4,
    tags: ['trap', 'formula'],
  },
];
