// src/topics/gradient-descent/questions.ts
import type { Question } from '../../engine/types';

export const gdQuestions: Question[] = [
  {
    id: 'gd-001',
    mode: 'gate-mcq',
    prompt: 'Gradient descent is used to minimize f(x) = x² starting from x₀ = 3 with learning rate η = 0.5. What is x after one update?',
    options: ['1.5', '0', '-1.5', '3'],
    answer: 'B',
    explanation: 'x₁ = x₀ − η·f′(x₀) = 3 − 0.5·(2·3) = 3 − 3 = 0. Option A forgets the factor 2 in the derivative; C uses wrong sign.',
    trapExplanations: {
      A: 'Forgets that f′(x) = 2x, using x² directly.',
      C: 'Uses the wrong sign in the update rule.',
      D: 'Assumes no update happens.',
    },
    concepts: ['gradient-descent', 'derivative', 'update rule'],
    difficulty: 2,
    tags: ['formula', 'numerical'],
  },
  {
    id: 'gd-002',
    mode: 'nat',
    prompt: 'Minimize f(x) = x² with η = 0.1, starting at x₀ = 5. Compute x₂ (after 2 updates). Enter your answer to 3 decimal places.',
    answer: 3.2,
    tolerance: 0.001,
    explanation: 'x₁ = 5 − 0.1·(2·5) = 4; x₂ = 4 − 0.1·(2·4) = 3.2.',
    concepts: ['gradient-descent'],
    difficulty: 2,
    tags: ['numerical'],
  },
  {
    id: 'gd-003',
    mode: 'conceptual-mcq',
    prompt: 'Which statement about gradient descent is TRUE?',
    options: [
      'A larger learning rate always speeds convergence',
      'Gradient descent is guaranteed to find the global minimum of any differentiable function',
      'For a convex function with suitable η, gradient descent converges to the global minimum',
      'The gradient points in the direction of steepest descent',
    ],
    answer: 'C',
    explanation: 'Convexity guarantees any local minimum is global; with a suitable η, GD converges there. A is false (too-large η diverges), B false (non-convex functions have local minima), D false — gradient points uphill; we move opposite.',
    trapExplanations: {
      A: 'η beyond the critical threshold diverges.',
      B: 'Only convex functions guarantee global convergence.',
      D: 'Gradient is steepest ASCENT; we take the negative.',
    },
    concepts: ['gradient-descent', 'convexity'],
    difficulty: 3,
    tags: ['conceptual', 'trap'],
  },
  {
    id: 'gd-004',
    mode: 'nat',
    prompt: 'For f(x) = x² and η = 0.1, starting at x₀ = 10: how many updates until |x| < 0.5? (Each update multiplies x by (1 − 2η) = 0.8.)',
    answer: 14,
    tolerance: 1,
    explanation: 'x_t = 10·(0.8)^t. Need 10·0.8^t < 0.5 → 0.8^t < 0.05 → t > ln(0.05)/ln(0.8) ≈ 13.4 → 14 updates.',
    concepts: ['gradient-descent', 'geometric series'],
    difficulty: 4,
    tags: ['numerical', 'indirect'],
  },
  {
    id: 'gd-005',
    mode: 'visual',
    prompt: 'The figure shows f(x) = x² with a candidate update arrow. If the arrow points RIGHT from x = −2, what happens to the cost after the update?',
    options: ['Increases', 'Decreases', 'Stays the same', 'Cannot be determined'],
    answer: 'B',
    explanation: 'At x = −2 the gradient is 2·(−2) = −4 (negative); moving right (positive direction) is opposite the gradient → descent → cost decreases.',
    trapExplanations: {
      A: 'Confusing the sign of the gradient with the direction of descent.',
    },
    concepts: ['gradient-descent', 'direction of descent'],
    difficulty: 3,
    tags: ['visual'],
  },
  {
    id: 'gd-006',
    mode: 'gate-mcq',
    prompt: 'Which is a necessary condition for gradient descent to converge on f(x) = x² with fixed η?',
    options: ['η < 1', 'η ≤ 1', 'η = 1', 'η ≥ 1'],
    answer: 'A',
    explanation: 'Convergence requires |1 − 2η| < 1 → 0 < η < 1. At η = 1 the update oscillates forever between x and −x.',
    trapExplanations: {
      B: 'η = 1 gives oscillation, not convergence.',
      D: 'η > 1 diverges.',
    },
    concepts: ['gradient-descent', 'convergence'],
    difficulty: 3,
    tags: ['formula', 'trap'],
  },
];
