// src/topics/svm-hard-margin/questions.ts
// Simulation anchors referenced below (nPerClass 12, margin 1.5, noise 0.45):
//   default seed 42: ‖w‖ = 1.567, margin = 1.276, γ = 0.638, 2 SVs (d9, d21);
//   seed 7: ‖w‖ = 1.466, margin = 1.365, 3 SVs (d0 class 0; d14, d22 class 1).
import type { Question } from '../../engine/types';

export const svmQuestions: Question[] = [
  {
    id: 'svm-001',
    mode: 'nat',
    prompt: 'A hard-margin SVM has weight vector w = (3, 4) and bias b = 0. What is the margin 2/‖w‖? (Enter the number.)',
    answer: 0.4,
    tolerance: 0.01,
    explanation: '‖w‖ = √(3² + 4²) = 5, so margin = 2/‖w‖ = 2/5 = 0.4. The margin is the full width of the band between the two parallel margin lines, in geometric (feature) units — NOT the per-point distance, which would be 0.2.',
    concepts: ['svm', 'margin', 'norm'],
    difficulty: 1,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'svm-002',
    mode: 'nat',
    prompt: 'An SVM with w = (1, 1) and b = −2 separates the plane. Classify the point x = (5, 0): class 1 has score w·x + b > 0, class 0 otherwise. Enter 0 or 1.',
    answer: 1,
    tolerance: 0.01,
    explanation: 'score = w·x + b = 1·5 + 1·0 − 2 = 3 > 0 ⇒ class 1. The score is the signed distance in score units; its SIGN decides the class, its magnitude is confidence.',
    concepts: ['svm', 'hyperplane', 'classification'],
    difficulty: 1,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'svm-003',
    mode: 'nat',
    prompt: 'A hyperplane has w = (2, 0) and b = −4, so the boundary is the vertical line x = 2. What is the GEOMETRIC margin γ of the point (1, 7)? (Enter the number; γ = |w·x + b| / ‖w‖.)',
    answer: 1,
    tolerance: 0.01,
    explanation: '|w·x + b| = |2·1 + 0·7 − 4| = |−2| = 2; ‖w‖ = 2; γ = 2/2 = 1. The geometric margin is the true perpendicular distance — here the point sits 1 unit left of the line x = 2. The FUNCTIONAL margin would be −2 (it does not include the norm), a common confusion.',
    concepts: ['svm', 'geometric margin', 'distance'],
    difficulty: 2,
    tags: ['numerical', 'trap'],
  },
  {
    id: 'svm-004',
    mode: 'conceptual-mcq',
    prompt: 'Why does maximizing the margin improve generalization (the core SVM argument)?',
    options: [
      'A large margin means the boundary is far from every training point, so small perturbations or noise cannot flip the classification — the separator is the most "stable" among all separating hyperplanes',
      'A large margin implies the training set must have been small, which automatically prevents overfitting',
      'Maximizing the margin is equivalent to maximizing the number of support vectors, which adds capacity',
      'The margin is the probability that a new point is classified correctly, so maximizing it maximizes accuracy directly',
    ],
    answer: 'A',
    explanation: 'The margin measures the clearance between the boundary and the data: the larger it is, the harder it is for a small shift in a point (or a new sample near the boundary) to cross the line. Theoretically, the generalization error is bounded by a term that grows with the boundary complexity and shrinks as the margin grows (margin-based bounds). In the simulation, the max-margin separator at ½‖w‖² = 1.228 (margin 1.276) is the unique most-robust line — a perceptron-style arbitrary separator with the same training accuracy would sit arbitrarily close to a support vector.',
    trapExplanations: {
      B: 'Dataset size and margin are independent; a large margin is a property of the separator, not of n.',
      C: 'The opposite: the max-margin solution has the MINIMUM number of effective constraints (2 support vectors on the default seed) — more SVs usually signals a tighter, less regular separator.',
      D: 'The margin is a geometric quantity, not a probability; the SVM maximizes a margin, not an estimated accuracy.',
    },
    concepts: ['svm', 'generalization', 'margin'],
    difficulty: 3,
    tags: ['conceptual', 'indirect'],
  },
  {
    id: 'svm-005',
    mode: 'gate-mcq',
    prompt: 'GATE-style: for a hard-margin SVM, which statement about the dual variables αᵢ is correct?',
    options: [
      'αᵢ > 0 exactly for the support vectors (points on the margin); all other points have αᵢ = 0 and do not influence the boundary',
      'αᵢ > 0 for every correctly classified training point',
      'αᵢ is proportional to the distance of xᵢ from the boundary, so far points get larger αᵢ',
      'αᵢ = 0 for support vectors because their constraints are active',
    ],
    answer: 'A',
    explanation: 'Complementary slackness (KKT): αᵢ[yᵢ(w·xᵢ+b) − 1] = 0. A point strictly inside its region has yᵢ(w·xᵢ+b) > 1 ⇒ αᵢ = 0; a support vector has yᵢ(w·xᵢ+b) = 1 and can carry αᵢ > 0. Since w = Σαᵢyᵢxᵢ, only the SVs shape the boundary — on the default seed exactly 2 of 24 points.',
    trapExplanations: {
      B: 'Most correctly classified points are NOT on the margin — their constraints are slack, so αᵢ = 0.',
      C: 'αᵢ is a Lagrange multiplier tied to the constraint being ACTIVE, not to distance; interior points get 0 regardless of how deep inside they sit.',
      D: 'Exactly backwards: active constraints (on the margin) are the ones that may have αᵢ > 0.',
    },
    concepts: ['svm', 'dual', 'kkt', 'support vectors'],
    difficulty: 3,
    tags: ['trap', 'conceptual'],
  },
  {
    id: 'svm-006',
    mode: 'matrix',
    prompt: 'Match each quantity to its geometric meaning for the hyperplane w·x + b = 0 (class 0 ↔ −1, class 1 ↔ +1).',
    options: [
      'w',
      'w / ‖w‖',
      'yᵢ(w·xᵢ + b)',
      'yᵢ(w·xᵢ + b) / ‖w‖',
    ],
    answer: ['normal vector to the boundary', 'unit normal pointing at class 1', 'functional margin (score × label)', 'geometric margin (true distance)'],
    explanation: 'w is perpendicular to the hyperplane and points toward the positive class; normalizing by ‖w‖ makes it the unit normal. The functional margin is the label-signed score; dividing by ‖w‖ converts it into the true perpendicular distance. In the simulation the unit normal makes an angle of 14.1° with the horizontal — the direction the max-margin optimization chose.',
    concepts: ['svm', 'linear algebra', 'normal vector'],
    difficulty: 2,
    tags: ['matrix'],
  },
  {
    id: 'svm-007',
    mode: 'visual',
    prompt: 'Run the default simulation (nPerClass 12, margin 1.5, noise 0.45, seed 42) and scrub to the final snapshot. Which points are the support vectors, and what is their distance from the boundary?',
    options: [
      'Exactly 2 points — d9 (class 0, near (−0.41, −0.40)) and d21 (class 1, near (0.83, −0.09)) — each at distance 0.638 = 1/‖w‖ from the boundary',
      'All 24 points, because hard-margin SVM uses the whole training set to define the boundary',
      'Only the 12 class-0 points, since class 0 is the negative class',
      'The 4 points closest to the origin, at distance 1.276 from the boundary',
    ],
    answer: 'A',
    explanation: 'Scrub the run: the amber rings mark the support vectors — exactly d9 and d21 on the default seed. Both sit on their margin lines at distance 0.638 = 1/‖w‖ (‖w‖ = 1.567), and the segment joining them is exactly the margin width 1.276. The closest NON-support point (d20) is 0.757 away — a clear visual gap. The run\'s 22 other points have αᵢ = 0 and do not shape the boundary at all.',
    trapExplanations: {
      B: 'Only points ON the margin become support vectors; interior points are irrelevant to the solution.',
      C: 'Both classes contribute support vectors — d9 from class 0, d21 from class 1.',
      D: 'The margin band is 1.276 wide, but each support vector sits 0.638 (half the band) from the boundary — the 1.276 figure is the band width, not the per-point distance.',
    },
    concepts: ['svm', 'support vectors', 'visualization'],
    difficulty: 2,
    tags: ['visual'],
  },
  {
    id: 'svm-008',
    mode: 'gate-mcq',
    prompt: 'GATE-style: the training data is scaled so every feature is multiplied by 2. How do the optimal weights and margin of the hard-margin SVM change?',
    options: [
      'The optimal weights HALVE (‖w′‖ = ‖w‖/2) and the margin DOUBLES; the boundary is unchanged and the invariant margin·‖w‖ = 2 is preserved',
      'The optimal weights double and the margin halves, so the boundary moves',
      'The optimal weights and the margin both double',
      'Nothing changes: the margin is scale-invariant by definition',
    ],
    answer: 'A',
    explanation: 'For scaled points x′ = 2x, the same geometric boundary is w′·x′ + b = 0 with w′ = w/2 (verify: w′·(2x) + b = w·x + b). So ‖w′‖ = ‖w‖/2, margin′ = 2/‖w′‖ = 2·margin, and margin′·‖w′‖ = 2 — the invariant the simulation measures exactly: at scale 2 the default run gives ‖w‖ = 0.783 (vs 1.567) and margin 2.553 (vs 1.276), same 14.1° boundary. Scaling DOWN by ½ is the framing that doubles ‖w‖.',
    trapExplanations: {
      B: 'Scaling the data up by 2 makes the features numerically larger, so a smaller weight achieves the same boundary — weights shrink, not grow.',
      C: 'Weights and margin move in OPPOSITE directions — their product is what is invariant.',
      D: 'The margin changes (it doubles); what is invariant is the product margin·‖w‖ = 2.',
    },
    concepts: ['svm', 'feature scaling', 'margin'],
    difficulty: 3,
    tags: ['trap', 'numerical'],
  },
  {
    id: 'svm-009',
    mode: 'conceptual-mcq',
    prompt: 'An SVM has 3 support vectors: two of class 1 (d14 at (0.95, 0.64), d22 at (1.17, 0.06)) and one of class 0 (d0 at (−0.26, −0.03)) — the seed-7 run in the simulator. What does this configuration imply about the optimal hyperplane?',
    options: [
      'The two class-1 support vectors lie on the SAME margin line (w·x + b = +1), so the weight vector is perpendicular to the segment d14–d22',
      'The two class-1 support vectors must lie on opposite sides of the boundary',
      'A 3-support-vector solution means the data is not linearly separable',
      'The class-0 support vector contributes nothing to w because it is alone',
    ],
    answer: 'A',
    explanation: 'The margin line for class 1 is the line w·x + b = +1; both d14 and d22 satisfy it. Subtracting the two equations gives w·(d14 − d22) = 0 — w is perpendicular to their connecting segment. That is exactly the 3-support-vector geometry the solver exploits: the optimal normal is perpendicular to a same-class pair segment. The seed-7 run achieves margin 1.365 with these 3 SVs.',
    trapExplanations: {
      B: 'Both class-1 SVs sit on the +1 margin line, which is entirely on the class-1 side — never opposite sides of the boundary.',
      C: '3 support vectors is perfectly normal for separable data in 2D (the general bound is d+1 = 3); separability is unchanged.',
      D: 'Every support vector carries αᵢ > 0 and contributes αᵢyᵢxᵢ to w — d0 is as essential as d14 and d22.',
    },
    concepts: ['svm', 'support vectors', 'geometry'],
    difficulty: 3,
    tags: ['conceptual', 'visual'],
  },
];
