// src/topics/logistic-regression/formulas.ts
import type { Formula } from '../../engine/types';

export const logisticFormulas: Formula[] = [
  {
    id: 'sigmoid',
    latex: '\\sigma(z) = \\frac{1}{1 + e^{-z}} = \\begin{cases} \\frac{1}{1 + e^{-z}} & z \\ge 0 \\\\[2pt] \\frac{e^{z}}{1 + e^{z}} & z < 0 \\end{cases}',
    symbols: [
      { symbol: 'z', meaning: 'log-odds score w·x + b', dimensions: 'real scalar' },
      { symbol: '\\sigma(z)', meaning: 'probability p(y = 1 | x) — the sigmoid squashes any real score into (0, 1)', dimensions: 'probability in (0,1)' },
    ],
    assumptions: ['z is finite (the stable piecewise form never computes e^−z for z < 0 or e^z for z > 0 in the overflow direction)'],
    failureCases: ['|z| huge → σ saturates to 0 or 1 (σ(30) ≈ 1 − 9×10⁻¹⁴, never exactly 1) — see sigmoid-derivative', 'z undefined (NaN) propagates'],
    connections: ['Logistic function', 'Log-odds'],
    whyWorks: 'σ is the cumulative distribution of the logistic distribution and the canonical link of the Bernoulli GLM. The piecewise form is numerically stable: for z ≥ 0 use 1/(1+e^−z); for z < 0 use e^z/(1+e^z) — the exponential never appears with a large POSITIVE argument, so no overflow. σ(0) = 0.5 exactly.',
  },
  {
    id: 'log-odds',
    latex: 'z = w \\cdot x + b = w_1 x_1 + w_2 x_2 + b',
    symbols: [
      { symbol: 'w', meaning: 'weight vector (feature influence on the log-odds)', dimensions: 'd = 2 here' },
      { symbol: 'x', meaning: 'feature vector (the two coordinates of the point)', dimensions: 'd = 2 here' },
      { symbol: 'b', meaning: 'bias/intercept — the log-odds offset (absorbs class prior)', dimensions: 'scalar' },
      { symbol: 'z', meaning: 'log-odds: ln(p/(1−p)) — the model is LINEAR in the log-odds', dimensions: 'real scalar' },
    ],
    assumptions: ['Features are z-scored for training — an exact affine reparametrization: z = Σwⱼxⱼ + b is IDENTICAL in standardized and original coordinates, so the sigmoid sees the same scores'],
    failureCases: ['b badly off (class imbalance) → boundary offset toward the majority class', 'unscaled features → poor GD conditioning (fixed by standardization)'],
    derivesFrom: ['sigmoid'],
    connections: ['GLM link functions'],
    whyWorks: 'Instead of modeling p directly, logistic regression models the log-odds as a linear function. Inverting p = 1/(1+e^−z) gives ln(p/(1−p)) = z = w·x + b — linearity in log-odds is the defining property, and the p = 0.5 contour is exactly the hyperplane z = 0.',
  },
  {
    id: 'likelihood',
    latex: 'L(w, b) = \\prod_{i=1}^{n} \\hat{y}_i^{\\,y_i}\\; (1 - \\hat{y}_i)^{\\,1 - y_i}, \\qquad \\hat{y}_i = \\sigma(w \\cdot x_i + b)',
    symbols: [
      { symbol: 'y_i', meaning: 'true label of point i (0 or 1)', dimensions: 'binary' },
      { symbol: '\\hat{y}_i', meaning: 'predicted probability σ(zᵢ)', dimensions: 'in (0,1)' },
      { symbol: 'L', meaning: 'likelihood — probability the model assigns to the observed labels', dimensions: 'in (0,1]' },
    ],
    assumptions: ['Labels are independent Bernoulli draws given x (the i.i.d. assumption)'],
    failureCases: ['any ŷ → 0 or 1 makes the product degenerate (hence the log), e.g. separable data → no finite maximizer'],
    derivesFrom: ['sigmoid', 'log-odds'],
    connections: ['Maximum likelihood estimation'],
    whyWorks: 'Each point contributes the probability of its OWN label: ŷᵢ when yᵢ = 1, (1−ŷᵢ) when yᵢ = 0 — compactly ŷᵢ^yᵢ(1−ŷᵢ)^(1−yᵢ). The product is the joint probability of the labels; maximizing it is the MLE. Because the factors are ≤ 1 the product tends to 0, which is why we work with the log (derivations: ce-from-mle).',
  },
  {
    id: 'cross-entropy',
    latex: 'L = -\\frac{1}{n}\\sum_{i=1}^{n} \\Big[ y_i \\log \\hat{y}_i + (1 - y_i) \\log(1 - \\hat{y}_i) \\Big]',
    symbols: [
      { symbol: 'y_i', meaning: 'true label (0 or 1)', dimensions: 'binary' },
      { symbol: '\\hat{y}_i', meaning: 'predicted probability σ(zᵢ)', dimensions: 'in (0,1)' },
      { symbol: 'L', meaning: 'mean cross-entropy — the loss we minimize (÷n is a scaling choice)', dimensions: '≥ 0' },
    ],
    assumptions: ['No penalty on the weights (unregularized logistic regression)'],
    failureCases: ['ŷ → 0 with y = 1 → −log ŷ → ∞ (prediction confidently wrong)', 'separable data → L → 0 while ‖w‖ → ∞ (the MLE does not exist)'],
    derivesFrom: ['likelihood'],
    connections: ['KL divergence', 'Information theory'],
    whyWorks: 'CE is −(1/n) times the log-likelihood: minimizing CE = maximizing the likelihood (MLE). Unlike squared error, CE is convex in w for the sigmoid model and punishes confident-wrong predictions with an unbounded cost — exactly the behaviour a classifier wants.',
  },
  {
    id: 'ce-stable',
    latex: 'L_i = y_i\\, \\operatorname{softplus}(-z_i) + (1 - y_i)\\, \\operatorname{softplus}(z_i), \\qquad \\operatorname{softplus}(z) = \\log(1 + e^{z}) \\;\\Big( = z + \\log(1 + e^{-z}) \\text{ for } z > 0 \\Big)',
    symbols: [
      { symbol: '\\operatorname{softplus}(z)', meaning: 'smooth approximation of max(0, z); its stable form never overflows', dimensions: '≥ 0' },
      { symbol: 'z_i', meaning: 'log-odds w·xᵢ + b', dimensions: 'real scalar' },
    ],
    assumptions: ['z finite'],
    failureCases: ['Naive −log ŷ with ŷ → 0 computes log(0) = −∞; the softplus form avoids this by construction'],
    derivesFrom: ['cross-entropy'],
    connections: ['Numerical stability'],
    whyWorks: 'Since −log σ(z) = log(1+e^−z) = softplus(−z) and −log(1−σ(z)) = log(1+e^z) = softplus(z), the per-point CE becomes y·softplus(−z) + (1−y)·softplus(z) — no log(0), no exp overflow. This is the form the engine actually evaluates.',
  },
  {
    id: 'ce-gradient',
    latex: '\\frac{\\partial L}{\\partial w} = \\frac{1}{n}\\sum_{i=1}^{n} (\\hat{y}_i - y_i)\\, x_i, \\qquad \\frac{\\partial L}{\\partial b} = \\frac{1}{n}\\sum_{i=1}^{n} (\\hat{y}_i - y_i)',
    symbols: [
      { symbol: '\\hat{y}_i - y_i', meaning: 'the residual "prediction − truth" — the (ŷ−y) factor of the famous result', dimensions: 'in (−1, 1)' },
      { symbol: 'x_i', meaning: 'feature vector of point i', dimensions: 'd = 2' },
      { symbol: '\\frac{\\partial L}{\\partial w}', meaning: 'gradient of mean CE — the direction of steepest ascent', dimensions: 'd-vector' },
    ],
    assumptions: ['CE loss (above); full-batch gradient'],
    failureCases: ['Saturated sigmoid → ŷ−y → {0, ±1} but σ′ → 0 kills the chain (see sigmoid-derivative) — vanishing gradients'],
    derivesFrom: ['cross-entropy', 'sigmoid-derivative'],
    connections: ['Gradient descent', 'Chain rule'],
    whyWorks: 'The sigmoid’s own derivative σ′(z) = σ(z)(1−σ(z)) cancels the 1/(ŷ(1−ŷ)) factors of the CE derivative, leaving the beautifully simple residual (ŷ−y) — derived step-by-step in derivations (ce-gradient-chain-rule). GD then moves weights opposite this gradient: θ ← θ − lr·∂L/∂θ.',
  },
  {
    id: 'sigmoid-derivative',
    latex: '\\sigma\'(z) = \\sigma(z)\\,\\big(1 - \\sigma(z)\\big) \\;\\longrightarrow\\; 0 \\;\\text{ as }\\; |z| \\to \\infty',
    symbols: [
      { symbol: '\\sigma\'(z)', meaning: 'slope of the sigmoid — maximum 1/4 at z = 0, collapses at the tails', dimensions: 'in (0, 1/4]' },
      { symbol: '\\sigma(z)(1-\\sigma(z))', meaning: 'the "sigmoid squeeze": probability of being wrong × right', dimensions: '≤ 1/4' },
    ],
    assumptions: ['σ the standard logistic function'],
    failureCases: ['|z| large → σ′ ≈ 0 → gradients vanish and GD crawls (saturated-sigmoid failure demo)', 'z ≈ 0 only → the model stays uncertain (underfit probability-wise)'],
    derivesFrom: ['sigmoid'],
    connections: ['Backpropagation', 'Vanishing gradients'],
    whyWorks: 'Differentiating σ = 1/(1+e^−z): σ′ = e^−z/(1+e^−z)² = σ(1−σ). This identity is the algebraic engine of the (ŷ−y) gradient: the CE derivative’s 1/(ŷ(1−ŷ)) is cancelled exactly by σ′. It also explains WHY CE beats MSE for classification: MSE’s gradient carries an extra σ′ factor that vanishes at the tails, while CE’s does not.',
  },
  {
    id: 'decision-boundary',
    latex: 'p = 0.5 \\;\\Longleftrightarrow\\; \\sigma(z) = 0.5 \\;\\Longleftrightarrow\\; z = 0 \\;\\Longleftrightarrow\\; w \\cdot x + b = 0',
    symbols: [
      { symbol: 'w \\cdot x + b = 0', meaning: 'a straight line in 2D (hyperplane in d-D) — the decision boundary', dimensions: 'line' },
      { symbol: '\\sigma(0)', meaning: 'sigmoid at z = 0 — exactly 0.5', dimensions: '0.5' },
    ],
    assumptions: ['Threshold chosen at 0.5 (the default decision rule; the threshold is a choice, see mistakes)'],
    failureCases: ['Non-linear class structure (ring data) → no straight line separates; boundary is the best linear compromise', 'class imbalance → the line shifts toward the minority class'],
    derivesFrom: ['sigmoid', 'log-odds'],
    connections: ['Perceptron', 'SVM (max-margin parallel)'],
    whyWorks: 'σ is strictly monotone, so the 0.5 contour of σ(z) is exactly the zero set of z — and z is affine in x, so the boundary is LINEAR. The probability heat (blue → red) is the smooth version of the hard 0/1 partition the boundary draws.',
  },
  {
    id: 'mle-ce',
    latex: '\\arg\\max_{w,b} \\prod_i \\hat{y}_i^{y_i}(1-\\hat{y}_i)^{1-y_i} \\;\\Longleftrightarrow\\; \\arg\\min_{w,b} \\frac{1}{n}\\sum_i \\Big[ -y_i \\log \\hat{y}_i - (1-y_i)\\log(1-\\hat{y}_i) \\Big]',
    symbols: [
      { symbol: '\\max \\prod', meaning: 'maximum likelihood — the MLE', dimensions: '—' },
      { symbol: '\\min \\frac{1}{n} \\sum', meaning: 'minimum cross-entropy — the CE minimizer', dimensions: '≥ 0' },
    ],
    assumptions: ['Bernoulli labels; i.i.d. data'],
    failureCases: ['Separable data → the argmax is not attained (weights escape to infinity) — CE decreases without bound'],
    derivesFrom: ['likelihood', 'cross-entropy'],
    connections: ['MLE', 'KL divergence'],
    whyWorks: 'The log is strictly increasing and turns the product into a sum; the 1/n and the minus sign just rescale and flip it. So the logistic-regression optimizer is literally a maximum-likelihood estimator — the GATE connection that unifies "why cross-entropy?" and "why probabilities?"',
  },
];
