// src/topics/logistic-regression/questions.ts
import type { Question } from '../../engine/types';

export const logisticQuestions: Question[] = [
  {
    id: 'log-001',
    mode: 'nat',
    prompt: 'Compute the sigmoid σ(z) = 1/(1+e^−z) at z = 0.5. (Enter the probability to 3 decimals.)',
    answer: 0.622,
    tolerance: 0.005,
    explanation: 'e^0.5 = 1.6487, so e^−0.5 = 0.60653 and σ(0.5) = 1/(1 + 0.60653) = 1/1.60653 = 0.6225. Symmetry check: σ(−0.5) = 1 − 0.6225 = 0.3775. The sigmoid maps any real score into (0,1) and is symmetric about the point (0, 0.5).',
    concepts: ['logistic-regression', 'sigmoid'],
    difficulty: 2,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'log-002',
    mode: 'nat',
    prompt: 'A logistic-regression model has w = (2, −1), b = 0.5. For the point x = (1, 3), what is the predicted confidence p = σ(w·x + b)? (Enter to 3 decimals.)',
    answer: 0.378,
    tolerance: 0.005,
    explanation: 'Log-odds z = w·x + b = 2·1 + (−1)·3 + 0.5 = −0.5. Then p = σ(−0.5) = 0.3775 (use e^−0.5/(1+e^−0.5), or the symmetry σ(−0.5) = 1 − σ(0.5) = 1 − 0.6225). Since p < 0.5 the predicted class is 0.',
    concepts: ['logistic-regression', 'log-odds', 'prediction'],
    difficulty: 2,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'log-003',
    mode: 'nat',
    prompt: 'Using the gradient ∂L/∂w = Σᵢ(ŷᵢ − yᵢ)·xᵢ (no 1/n scaling): residuals (ŷᵢ − yᵢ) = [0.2, −0.1, 0.3] for points x₁ = (1, 2), x₂ = (3, 4), x₃ = (5, 6). What is ∂L/∂w₁ (the gradient on the first feature)?',
    answer: 1.4,
    tolerance: 0.01,
    explanation: 'Each point contributes its residual times its FIRST coordinate: 0.2·1 + (−0.1)·3 + 0.3·5 = 0.2 − 0.3 + 1.5 = 1.4. (For the second feature: 0.2·2 + (−0.1)·4 + 0.3·6 = 0.4 − 0.4 + 1.8 = 1.8.) The gradient is the residual-weighted sum of the feature vectors — one scalar per weight.',
    concepts: ['logistic-regression', 'gradient', 'matrix operations'],
    difficulty: 3,
    tags: ['matrix', 'numerical', 'indirect'],
  },
  {
    id: 'log-004',
    mode: 'nat',
    prompt: 'For the bias update ∂L/∂b = Σᵢ(ŷᵢ − yᵢ), residuals are [0.2, −0.1, 0.3, −0.4]. What is ∂L/∂b? (Note: this is a deliberately interesting answer.)',
    answer: 0,
    tolerance: 0.01,
    explanation: '∂L/∂b = 0.2 − 0.1 + 0.3 − 0.4 = 0. This is not a coincidence: at the optimum the gradient on the bias must vanish, so Σŷᵢ = Σyᵢ — the model’s AVERAGE predicted probability equals the empirical fraction of positives (probability calibration). This is the same identity the "p ≈ empirical rate" calibration check uses.',
    concepts: ['logistic-regression', 'gradient', 'calibration'],
    difficulty: 3,
    tags: ['numerical', 'conceptual'],
  },
  {
    id: 'log-005',
    mode: 'conceptual-mcq',
    prompt: 'Why is mean squared error (MSE) a poor loss for logistic regression, even though it is the default for linear regression?',
    options: [
      'Because CE is the negative log-likelihood of the Bernoulli model (so its minimizer is the MLE), while MSE+sigmoid is non-convex and its gradient carries an extra σ′ factor that vanishes when the sigmoid saturates',
      'Because MSE is always negative for probabilities',
      'Because MSE penalizes correct predictions more than wrong ones',
      'Because MSE requires the targets to be continuous, and 0/1 labels are integers',
    ],
    answer: 'A',
    explanation: 'Two independent strikes against MSE: (1) Optimization — with a sigmoid squashing, the squared-error surface is non-convex and its gradient contains the extra factor σ′(z) = σ(1−σ), which → 0 at the tails: exactly when the model is confident-but-wrong the gradient is smallest (vanishing gradients). (2) Statistics — MSE does not correspond to any natural probabilistic model of binary labels, while CE is exactly −(1/n)·log-likelihood, so minimizing CE is the MLE.',
    trapExplanations: {
      B: 'MSE is a sum of squares — always ≥ 0, never negative for probabilities.',
      C: 'MSE penalizes wrong predictions quadratically, but it penalizes CONFIDENT errors less than CE does, and it rewards overconfidence on correct ones.',
      D: 'Integers are perfectly valid numeric targets for a least-squares fit; the problem is the model class and the loss geometry, not the data type.',
    },
    concepts: ['logistic-regression', 'loss functions', 'cross-entropy'],
    difficulty: 3,
    tags: ['conceptual', 'trap'],
  },
  {
    id: 'log-006',
    mode: 'matrix',
    prompt: 'With d = 2 features, the gradient ∂L/∂w = (1/n)Σᵢ(ŷᵢ − yᵢ)xᵢ is a vector of what shape?',
    options: [
      'A d-vector (one component per weight), plus a separate scalar ∂L/∂b for the bias',
      'A scalar — the gradient is a single number',
      'An n-vector — one entry per training point',
      'A (d+1) × n matrix — one column per point',
    ],
    answer: 'A',
    explanation: 'Each point contributes its residual times its d-dimensional feature vector, and the sum of d-vectors is a d-vector: ∂L/∂w ∈ R^d. The bias lives in its own coordinate, ∂L/∂b = (1/n)Σ(ŷᵢ − yᵢ) ∈ R. Together they are the d+1 parameters the update rule touches — the same shape as θ = [w₁, w₂, b].',
    trapExplanations: {
      B: 'It is a vector — there are as many components as there are weights.',
      C: 'The per-point contributions are summed over i; the result does not depend on n as a dimension.',
      D: 'No matrix is built — the sum collapses the n dimension.',
    },
    concepts: ['logistic-regression', 'gradient', 'matrix dimensions'],
    difficulty: 2,
    tags: ['matrix'],
  },
  {
    id: 'log-007',
    mode: 'visual',
    prompt: 'In the simulation, drag the margin slider from 0.5 to 4 (keep noise small). What do you observe about the decision boundary and the probability heat?',
    options: [
      'The clusters move apart, the boundary stays roughly midway between them, and the band of points with p near 0.5 (the purple region) narrows — separation makes the model confident',
      'The boundary rotates to become horizontal as the margin grows',
      'The boundary moves to hug one cluster completely, classifying everything as one class',
      'The boundary disappears once the margin exceeds the noise',
    ],
    answer: 'A',
    explanation: 'Margin separates the cluster centres; the optimal boundary sits near the midpoint x₁ ≈ 0 where the two Gaussians cross. Larger margin → the crossing region has less probability mass → fewer points with z near 0 → fewer purple (p ≈ 0.5) points and sharper blue/red saturation. The heat band narrowing IS the probability story of separation.',
    trapExplanations: {
      B: 'The boundary stays near-vertical (the separating direction is x₁); margin does not rotate it.',
      C: 'The boundary tracks the Bayes-optimal midpoint; it does not collapse onto a cluster unless the class priors are heavily imbalanced.',
      D: 'The boundary always exists — it is the p = 0.5 level set, even when the model is uncertain.',
    },
    concepts: ['logistic-regression', 'decision boundary', 'margin'],
    difficulty: 2,
    tags: ['visual'],
  },
  {
    id: 'log-008',
    mode: 'gate-mcq',
    prompt: 'GATE-style statement: "Because the sigmoid maps R into (0,1), a sufficiently confident logistic-regression model outputs exactly p = 1 for z = 30." True or false?',
    options: [
      'False — σ(z) approaches 1 asymptotically: σ(30) ≈ 1 − 9×10⁻¹⁴ but never equals 1 for any finite z; p = 1 (and p = 0) are limits, not outputs',
      'True — for z > 10 the sigmoid rounds to exactly 1 in floating point',
      'True — the sigmoid reaches 1 whenever z exceeds the margin',
      'False — the sigmoid saturates to 0.5 for large z, not 1',
    ],
    answer: 'A',
    explanation: 'σ(z) = 1/(1+e^−z) is strictly between 0 and 1 for every FINITE z: σ(30) = 1/(1+e^−30) ≈ 0.999999999999906 (≈ 1 − 9.4×10⁻¹⁴), still not 1. The practical consequence is the saturation trap: near the tails the slope σ′(z) = σ(1−σ) ≈ 0, so the CE gradient (ŷ−y) ≈ 0 and gradient descent crawls — even though the model is already confident. "Confident" and "saturated" are where learning slows down.',
    trapExplanations: {
      B: 'Floating point may round σ(30) to 1.0 in storage, but that is an artefact, not the mathematical behaviour — and the failure mode it produces (vanishing gradient) is what matters.',
      C: 'There is no threshold beyond which σ "becomes" 1; the approach is asymptotic.',
      D: 'σ saturates to 1 for large positive z and to 0 for large negative z — never to 0.5.',
    },
    concepts: ['logistic-regression', 'sigmoid', 'saturation'],
    difficulty: 3,
    tags: ['trap', 'conceptual'],
  },
];
