// src/topics/lasso-regression/questions.ts
import type { Question } from '../../engine/types';

export const lassoQuestions: Question[] = [
  {
    id: 'lasso-001',
    mode: 'nat',
    prompt: 'Apply the soft-threshold operator: given the normalized correlation z = 3.2 and penalty λ = 1.0, the new standardized coefficient is w̃ = S(z, λ) = sign(z)·max(|z| − λ, 0). Compute w̃.',
    answer: 2.2,
    tolerance: 0.01,
    explanation: 'sign(3.2) = +1 and max(|3.2| − 1.0, 0) = max(2.2, 0) = 2.2, so w̃ = +1·2.2 = 2.2. The coefficient is shrunk toward zero by exactly λ = 1.0 but survives because |z| = 3.2 > λ.',
    concepts: ['lasso-regression', 'soft-threshold'],
    difficulty: 2,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'lasso-002',
    mode: 'nat',
    prompt: 'Apply the soft-threshold operator: given z = 0.8 and λ = 1.0, compute w̃ = S(z, λ) = sign(z)·max(|z| − λ, 0).',
    answer: 0,
    tolerance: 0.01,
    explanation: '|0.8| − 1.0 = −0.2, and max(−0.2, 0) = 0. Since |z| = 0.8 ≤ λ = 1.0 the coefficient is pulled to EXACTLY zero — the mechanism behind lasso feature selection.',
    concepts: ['lasso-regression', 'soft-threshold', 'sparsity'],
    difficulty: 2,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'lasso-003',
    mode: 'conceptual-mcq',
    prompt: 'Why can lasso produce EXACTLY zero coefficients while ridge regression cannot?',
    options: [
      'The L1 penalty is differentiable everywhere, so the optimum always moves slightly',
      'The L1 penalty has a non-differentiable kink at 0 — when the subgradient interval contains 0, the coefficient sits exactly on the axis',
      'Ridge converges slower, so it never reaches zero',
      'Lasso uses gradient descent and ridge uses a closed form',
    ],
    answer: 'B',
    explanation: 'At θⱼ = 0 the subgradient of λ|θⱼ| is the whole interval [−λ, λ]. If the MSE gradient −z satisfies |z| ≤ λ, then 0 ∈ ∂J at θⱼ = 0 — a stationary point with the coordinate EXACTLY at zero. Ridge\'s smooth quadratic penalty has no such interval, so zero is a measure-zero event.',
    trapExplanations: {
      A: 'The kink is precisely what enables exact zeros — L1 is NOT differentiable at 0.',
      C: 'Convergence speed has nothing to do with the existence of exact zeros in the optimum.',
      D: 'Both can be solved many ways; the sparsity difference is a property of the objective, not the algorithm.',
    },
    concepts: ['lasso-regression', 'subgradient', 'sparsity'],
    difficulty: 3,
    tags: ['conceptual'],
  },
  {
    id: 'lasso-004',
    mode: 'visual',
    prompt: 'On a coefficient-path plot (horizontal axis = λ, one line per feature\'s coefficient), feature f\'s path crosses exactly zero at λ = 0.8 and stays at zero for every larger λ. What is the best inference?',
    options: [
      'Feature f has the largest true effect of all features',
      'The magnitude of feature f\'s standardized OLS coefficient is approximately 0.8 — it gets zeroed once λ exceeds it',
      'λ must be increased to at least 10 before any selection happens',
      'This plot must be from ridge regression, since only ridge paths can hit zero',
    ],
    answer: 'B',
    explanation: 'A coefficient is zeroed exactly when its normalized correlation |ρ/n| ≤ λ, and the path hits 0 where |ρ/n| ≈ λ. Since |w̃_f| ≈ 0.8, the feature is zeroed for any λ ≥ 0.8 — and it is among the LEAST important features (it disappears first).',
    trapExplanations: {
      A: 'Being zeroed FIRST means the feature is the LEAST important, not the most.',
      C: 'Selection happens at the λ where the first path hits zero — here 0.8, well below 10.',
      D: 'Only lasso (L1) paths can hit exact zero; ridge paths only approach zero asymptotically.',
    },
    concepts: ['lasso-regression', 'coefficient path', 'feature selection'],
    difficulty: 3,
    tags: ['visual'],
  },
  {
    id: 'lasso-005',
    mode: 'gate-mcq',
    prompt: 'In the classic constraint-geometry figure, the lasso solution often lies EXACTLY on a coordinate axis while the ridge solution does not. Why?',
    options: [
      'The L1 constraint region is a diamond with vertices on the axes — the optimum can touch a vertex, setting one coordinate to 0',
      'The L2 circle has corners that force zeros',
      'L1 shrinks every coefficient uniformly so they all reach zero together',
      'The ellipse is drawn incorrectly in the ridge case',
    ],
    answer: 'A',
    explanation: 'Level sets of the quadratic loss are ellipses centered at θ̂_OLS. The L1 ball ‖θ‖₁ ≤ t is a diamond whose vertices lie on the axes; the first touching contour generically meets a vertex, giving an exact zero. The L2 ball is a smooth circle — tangency happens on the arc, so all coordinates stay nonzero.',
    trapExplanations: {
      B: 'The circle has NO corners — that is exactly why ridge never zeroes.',
      C: 'L1 does not shrink uniformly; it soft-thresholds (constant shift then clamp at 0).',
      D: 'Both figures share the same loss ellipses; only the constraint shape differs.',
    },
    concepts: ['lasso-regression', 'L1 vs L2', 'constraint geometry'],
    difficulty: 3,
    tags: ['conceptual', 'trap'],
  },
  {
    id: 'lasso-006',
    mode: 'conceptual-mcq',
    prompt: 'Two features are nearly perfectly correlated (corr ≈ 1) and both predict y. What does lasso typically do, and why?',
    options: [
      'Keeps both with equal weights to preserve symmetry',
      'Arbitrarily selects ONE of them and zeroes the other — the choice is driven by tiny noise asymmetries, not by real signal',
      'Fails with a numerical error because the design matrix is singular',
      'Automatically averages the two features into one',
    ],
    answer: 'B',
    explanation: 'Nearly equal information means the two normalized correlations are almost identical. The soft-threshold breaks the tie at whatever small difference the noise introduces: whichever correlation is slightly larger in magnitude keeps its coefficient, the other is zeroed. The split is not uniquely determined by the data — a classic lasso limitation.',
    trapExplanations: {
      A: 'Lasso is not symmetric in this case; it picks one and drops the other.',
      C: 'Lasso (unlike OLS) does not need XᵀX invertible — coordinate descent handles collinearity, it just selects arbitrarily.',
      D: 'Lasso does no averaging; it is a selector, not an aggregator.',
    },
    concepts: ['lasso-regression', 'collinearity', 'feature selection'],
    difficulty: 4,
    tags: ['conceptual', 'trap'],
  },
];
