// src/topics/svm-soft-margin/questions.ts
import type { Question } from '../../engine/types';

export const svmSoftQuestions: Question[] = [
  {
    id: 'svm-soft-001',
    mode: 'nat',
    prompt: 'A point has signed margin y·f(x) = 0.25. What is its hinge loss max(0, 1 − y·f(x))? (Enter the exact value.)',
    answer: 0.75,
    tolerance: 1e-6,
    explanation: 'hinge = max(0, 1 − 0.25) = max(0, 0.75) = 0.75. The point is inside the margin band on the CORRECT side (0 < y·f < 1), so it pays a partial slack 0.75 — this is exactly the soft-margin tradeoff: hard margin would refuse this point, soft margin charges it 0.75·C.',
    concepts: ['svm', 'hinge-loss', 'slack'],
    difficulty: 1,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'svm-soft-002',
    mode: 'nat',
    prompt: 'A misclassified point has signed margin y·f(x) = −0.5. What is its hinge loss? (Enter the exact value.)',
    answer: 1.5,
    tolerance: 1e-6,
    explanation: 'hinge = max(0, 1 − (−0.5)) = 1.5. Since the point is on the wrong side of the boundary, y·f < 0 and the loss exceeds 1 — its slack ξ ≥ 1, the "misclassified" regime of the slack picture.',
    concepts: ['svm', 'hinge-loss', 'slack'],
    difficulty: 1,
    tags: ['numerical', 'formula'],
  },
  {
    id: 'svm-soft-003',
    mode: 'conceptual-mcq',
    prompt: 'In the soft-margin SVM objective ½‖w‖² + C·Σξᵢ, what happens to the bias–variance balance as C is INCREASED?',
    options: [
      'Variance increases and bias decreases — larger C chases the training points (narrower margin, more sensitivity to noise)',
      'Variance decreases and bias increases — larger C is more regularization',
      'Both bias and variance decrease monotonically',
      'Neither changes — C only rescales the objective',
    ],
    answer: 'A',
    explanation: 'Larger C makes each unit of slack more expensive, so the solver prefers a narrow margin with few violations — the boundary bends to fit the data (low bias, high variance). Smaller C allows slack, giving a wide stable margin (high bias, low variance). C acts like the INVERSE of a regularization strength λ: C ↑ ⇔ λ ↓.',
    trapExplanations: {
      B: 'That describes C decreasing, or equivalently λ increasing — the C↔1/λ duality is exactly inverted here.',
      C: 'There is no free lunch: one side of the tradeoff always moves against the other.',
      D: 'C sets the price of slack; the fitted w, b and the margin demonstrably move with it.',
    },
    concepts: ['svm', 'regularization', 'bias-variance'],
    difficulty: 3,
    tags: ['conceptual', 'trap'],
  },
  {
    id: 'svm-soft-004',
    mode: 'gate-mcq',
    prompt: 'GATE-style statement: "In a soft-margin SVM, setting C = 0 is equivalent to the hard-margin SVM." Is this true?',
    options: [
      'False — C = 0 makes every violation free, so the optimal solution is w = 0, b = 0 (a degenerate constant model); hard margin requires C → ∞',
      'True — the margin constraint y·f ≥ 1 is unchanged by C',
      'True — C = 0 removes the slack term but keeps ½‖w‖², which is the hard-margin objective',
      'False — C = 0 makes the problem non-convex',
    ],
    answer: 'A',
    explanation: 'With C = 0 the objective is just ½‖w‖² (slack costs nothing), minimized at w = 0 — no classification at all. The hard-margin solution needs violations FORBIDDEN, i.e. C → ∞ so the slack term dominates everything except the zero-slack optimum. C = 0 and C = ∞ sit at opposite ends of the path.',
    trapExplanations: {
      B: 'C does not change the constraint inequality, but it changes whether the solver is allowed to violate it.',
      C: 'With C = 0 the slack term vanishes, so the optimum ignores the constraints entirely (w = 0).',
      D: 'The problem stays convex; it simply degenerates to w = 0.',
    },
    concepts: ['svm', 'soft-margin', 'C-parameter'],
    difficulty: 3,
    tags: ['trap', 'conceptual'],
  },
  {
    id: 'svm-soft-005',
    mode: 'conceptual-mcq',
    prompt: 'What does the soft margin allow that the hard margin fundamentally cannot, on non-separable data?',
    options: [
      'A unique finite solution even when no line separates the two classes perfectly — by paying a bounded slack cost C·Σξᵢ for the unavoidable violations',
      'A perfect fit to any dataset by raising the polynomial degree',
      'A zero training error on every dataset',
      'A non-convex objective that always finds the global optimum faster',
    ],
    answer: 'A',
    explanation: 'The hard-margin problem is infeasible when the data is not linearly separable (no line has y·f ≥ 1 everywhere). The soft margin replaces "must" with "pay C per unit of violation", which is feasible for ANY finite dataset — the optimal w, b, ξ exist and are unique because the objective stays convex.',
    trapExplanations: {
      B: 'Raising the degree is a kernel/feature-space idea, not what the slack does.',
      C: 'Soft margin trades a small number of violations for a good margin; it does not guarantee (or want) zero training error.',
      D: 'The objective stays convex — that is precisely why the soft margin is solvable.',
    },
    concepts: ['svm', 'soft-margin', 'feasibility'],
    difficulty: 3,
    tags: ['conceptual'],
  },
  {
    id: 'svm-soft-006',
    mode: 'visual',
    prompt: 'In the simulation, turn the Outlier toggle ON and scrub C from 0.01 to 1000. Which statement best matches what you observe?',
    options: [
      'At small C the margin band is wide and the outlier sits far inside/wrong-side with a long orange slack line; as C grows the band shrinks, the slack lines shorten and the boundary rotates to reduce the outlier\'s penalty',
      'The margin band and the decision line never change — C only changes the objective value',
      'At large C the outlier disappears from the plot',
      'At small C the two clusters merge into one',
    ],
    answer: 'A',
    explanation: 'This is the C-animation: with slack cheap (small C) the solver keeps the wide margin of the clean clusters and simply writes off the outlier (long slack line, ξ ≥ 1). Raising C makes that slack expensive, so the boundary tightens and rotates to push the outlier toward its own side at the price of a smaller margin — exactly the bias–variance story playing out in front of you. (The exact numbers are reported in the narration and the margin metric.)',
    trapExplanations: {
      B: 'C moves the fitted (w, b): margin, slack lines, support vectors and boundary all change as you scrub.',
      C: 'The outlier stays in the data — what changes is how much the boundary tries to accommodate it.',
      D: 'The data generator is independent of C; the clusters never move.',
    },
    concepts: ['svm', 'C-sweep', 'margin'],
    difficulty: 2,
    tags: ['visual'],
  },
  {
    id: 'svm-soft-007',
    mode: 'gate-mcq',
    prompt: 'A point with y·f(x) = 3 has hinge loss 0, but the logistic loss ln(1 + e^(−y·f)) ≈ ln(1 + e⁻³) is still ≈ 0.0486 > 0. Why does the SVM not care about this point while logistic regression still does?',
    options: [
      'Hinge loss is flat (zero gradient) once y·f ≥ 1 — the margin band already "satisfied" the point; logistic loss never reaches exactly 0, so every point keeps pulling on the boundary',
      'Because SVM is a large-margin method and logistic is not',
      'Because logistic regression uses squared loss for confident points',
      'Hinge loss is non-convex, so it ignores far points',
    ],
    answer: 'A',
    explanation: 'Both losses are convex surrogates, but they differ beyond the margin: hinge is EXACTLY 0 for y·f ≥ 1 (its subgradient is 0), while the logistic loss approaches 0 asymptotically and keeps a nonzero gradient for every point. That is why an SVM solution is determined only by support vectors near the band, whereas logistic regression is influenced by all points — a frequent GATE contrast question.',
    trapExplanations: {
      B: '"Large margin" is the symptom; the mechanism is the flat region of the hinge.',
      C: 'Logistic uses cross-entropy (log-loss), not squared loss.',
      D: 'Hinge is convex — its flat region is a property of the maximum, not non-convexity.',
    },
    concepts: ['svm', 'logistic-regression', 'loss-functions'],
    difficulty: 4,
    tags: ['indirect', 'conceptual'],
  },
  {
    id: 'svm-soft-008',
    mode: 'nat',
    prompt: 'For a fitted soft-margin model, one point has slack ξᵢ = 1.7. Is it inside the margin band but correctly classified, or misclassified? (Answer 1 for inside-band-correct, 2 for misclassified.)',
    answer: 2,
    tolerance: 1e-6,
    explanation: 'ξᵢ ≥ 1 ⟺ 1 − y·f ≥ 1 ⟺ y·f ≤ 0, i.e. the point is on the wrong side of the decision boundary — misclassified. Only 0 < ξᵢ < 1 means inside the band but correctly classified. This threshold (ξ = 1) is the dividing line of the slack picture and a common trap in GATE.',
    concepts: ['svm', 'slack', 'misclassification'],
    difficulty: 2,
    tags: ['numerical', 'formula'],
  },
];
